import { OrderDomainModel } from '@esp/orders/types';

export const MOCK_ORDER: OrderDomainModel = {
  Id: 502188569,
  Type: 'order',
  Number: '2023-12301007-Enc',
  Date: '2022-04-19T00:00:00Z',
  InHandsDate: '2022-05-29T11:00:00Z',
  Salespersons: [
    {
      Id: 134577,
      Name: 'Franklin Arsenault',
    },
  ],
  Discount: 0,
  Status: 'Open',
  BillingContact: {
    Id: 514515620,
    Name: '(FIRST) (LAST)',
    CompanyName: '000000000123',
    EmailAddress: 'asdsad@asdsad.ds',
    Address: {
      Id: 0,
      Line1: '12300 Bermuda Rd',
      Line2: 'BillingAddress.Line2',
      City: 'Henderson',
      County: 'Clark County',
      State: 'NV',
      PostalCode: '89044',
      Country: 'United States',
      CountryType: 'US',
      Phone: {
        Id: 0,
        Type: 'Mobile',
        PhoneCode: '1',
        Country: 'US',
        Number: '444333444',
      },
      IsPrimary: false,
    },
  },
  AcknowledgementContact: {
    Id: 514515606,
    Name: '(FIRST) (LAST)',
    CompanyName: '000000000123',
    EmailAddress: 'asdsad@asdsad.ds',
    Address: {
      Id: 0,
      Line1: '12300 Bermuda Rd',
      City: 'Henderson',
      County: 'Clark County',
      State: 'NV',
      PostalCode: '89044',
      Country: 'United States',
      CountryType: 'US',
      Phone: {
        Id: 0,
        Type: 'Mobile',
        PhoneCode: '1',
        Country: 'US',
        Number: '234654345',
      },
      IsPrimary: false,
    },
  },
  ShippingContact: {
    Id: 514515621,
    Name: '#1 We Buy Anything',
    CompanyName: '123testAdam',
    EmailAddress: 'ayay-ron@asicentral.com',
    Address: {
      Id: 0,
      Line1: '4800 E Street Rd',
      City: 'Feasterville-Trevose',
      State: 'PA',
      PostalCode: '19053',
      Country: 'United States',
      CountryType: 'US',
      Phone: {
        Id: 0,
        Type: 'Mobile',
        PhoneCode: '1',
        Country: 'US',
        Number: '215-555-5555',
      },
      IsPrimary: false,
    },
    Company: {
      IsCompany: true,
      IsPerson: false,
      Id: 513567495,
      Name: '123testAdam',
      Addresses: [
        {
          Id: 506721367,
          Name: '123testAdam',
          City: '',
          State: '',
          PostalCode: '',
          CountryType: '',
          Phone: {
            Id: 510435905,
            Type: 'Other',
            PhoneCode: '1',
            Country: 'CA',
            IsPrimary: false,
          },
          IsPrimary: true,
          Type: 'GNRL',
        },
      ],
      Phones: [],
      Emails: [
        {
          Id: 508605143,
          Address: 'test@gmail.com',
          IsPrimary: true,
          Type: 'Work',
        },
      ],
      OwnerId: 134577,
      AccessLevel: 'Everyone',
      IsVisible: true,
      IsEditable: true,
    },
  },
  InquiryContact: {
    Id: 514515337,
    Name: 'Test Arsenault',
    CompanyName: 'ASI Corporate',
    EmailAddress: 'test@email.com',
    Address: {
      Id: 0,
      Line1: '12300 Bermuda Rd',
      City: 'Henderson',
      County: 'Clark County',
      State: 'NV',
      PostalCode: '89044',
      Country: 'United States',
      CountryType: 'US',
      Phone: {
        Id: 0,
        Type: 'Mobile',
        PhoneCode: '1',
        Country: 'US',
        Number: '444333444',
      },
      IsPrimary: false,
    },
  },
  ShippingSameAsBilling: false,
  AcknowledgementSameAsBilling: false,
  ReorderType: 'New',
  CreateDate: '2022-04-19T08:53:49.047Z',
  CreatedBy: 'Test Arsenault',
  UpdateDate: '2022-04-20T11:48:58.5157316Z',
  UpdatedBy: 'Franklin Arsenault',
  Customer: {
    CreditLimit: 0,
    ShippingAccounts: [],
    Links: [
      {
        Id: 504810381,
        Comment: 'Primary Contact',
        To: {
          IsCompany: false,
          IsPerson: true,
          Id: 513567496,
          Name: 'Test Test',
          Addresses: [],
          Phones: [],
          Emails: [],
          OwnerId: 134577,
          AccessLevel: 'Everyone',
          IsVisible: false,
          IsEditable: false,
        },
        Title: 'Primary Contact',
        IsEditable: false,
      },
    ],
    IsCustomer: true,
    IsSupplier: false,
    IsDecorator: false,
    IsProspect: false,
    IsAsiMember: false,
    CanEditVisibility: true,
    IsTaxExempt: false,
    TaxCertificates: [],
    WebsiteContactCount: 0,
    ProofType: 'Blank',
    PrimaryBrandColor: '#6A7281 ',
    IsCompany: true,
    IsPerson: false,
    Id: 513567495,
    Name: '123testAdam',
    IsActive: true,
    CreateDate: '2022-04-19T07:19:28.143Z',
    UpdateDate: '2022-04-19T07:19:29.887Z',
    LastActivityDate: '2022-04-19T07:19:29.883Z',
    Version: 114528733,
    Tags: [],
    Addresses: [
      {
        Id: 506721367,
        Name: '123testAdam',
        City: '',
        State: '',
        PostalCode: '',
        CountryType: '',
        Phone: {
          Id: 510435905,
          Type: 'Other',
          PhoneCode: '1',
          Country: 'CA',
          IsPrimary: false,
        },
        IsPrimary: true,
        Type: 'GNRL',
      },
    ],
    Phones: [],
    Emails: [
      {
        Id: 508605143,
        Address: 'test@gmail.com',
        IsPrimary: true,
        Type: 'Work',
      },
    ],
    Websites: [],
    Owner: {
      Id: 0,
      Name: '(Unknown)',
    },
    Creator: {
      Id: 0,
      Name: '(Unknown)',
    },
    OwnerId: 134577,
    AccessLevel: 'Everyone',
    IsVisible: true,
    IsEditable: true,
  },
} as unknown as OrderDomainModel;
