import { produce } from 'immer';

import { PriceGrid } from '@cosmos/types-common';
import {
  LikeDislike,
  PresentationProduct,
  PresentationProductAttribute,
} from '@esp/presentations/types';

const MOCK_PRESENTATION_PRODUCT: Partial<PresentationProduct> = {
  Id: 500000094,
  ProductId: 553064391,
  IsVisible: false,
  ShowMinMaxRange: true,
  AdjustmentType: 'profit-margin',
  Adjustment: 0,
  RoundPricesToTwoDecimal: true,
  Sequence: 7,
  Note: 'This is a sample Note',
  Supplier: { ExternalId: 593, Id: 1 } as PresentationProduct['Supplier'],
  Like: LikeDislike.None,
  Name: 'Cap America Cable Knit',
  Description:
    'Top off a great branded campaign with one of our stylish quality caps! This Cap America winter hat is crafted from a soft and warm polyester, cotton and spandex blend. It has a cable knit design with a fleece ear band and a faux fur pom-pom on top. Choose from four cool colors and add your school, sports team, organizational or company logo, emblem or message to create a sporty branded gift or giveaway for marketing and social activities and events.',
  Summary:
    'Cap America polyester/cotton/spandex cable knit cap with faux fur pom-pom.',
  Number: '26208',
  DefaultMedia: {
    IsVisible: false,
    Sequence: 0,
    Id: 42781923,
    Type: 'IM',
    Url: 'https://media.asicdn.com/images/jpgo/42780000/42781923.jpg',
    IsPrimary: true,
    IsVirtualSampleReady: false,
    Attributes: [839937094],
    IsAvailable: false,
  },
  LowestPrice: {
    IsVisible: false,
    Sequence: 0,
    Price: 16.9,
    Cost: 8.45,
    DiscountCode: 'P',
    DiscountPercent: 0.5,
    CurrencyCode: 'USD',
    IsUndefined: false,
    Quantity: { From: 1296, To: 2147483647 },
  },
  HighestPrice: {
    IsVisible: false,
    Sequence: 0,
    Price: 17.7,
    Cost: 8.85,
    DiscountCode: 'P',
    DiscountPercent: 0.5,
    CurrencyCode: 'USD',
    IsUndefined: false,
    Quantity: { From: 48, To: 95 },
  },
  UpdateDate: '2021-07-02T23:38:40.357Z',
  PublishDate: '2021-07-02T19:38:40.84Z',
  Media: [
    {
      IsVisible: true,
      Sequence: 0,
      Id: 44549144,
      Type: 'IM',
      Url: 'https://media.asicdn.com/images/jpgo/44540000/44549144.jpg',
      IsPrimary: true,
      IsVirtualSampleReady: false,
      Attributes: [],
      IsCustom: false,
      IsAvailable: false,
    },
    {
      IsVisible: true,
      Sequence: 1,
      Id: 44549145,
      Type: 'IM',
      Url: 'https://media.asicdn.com/images/jpgo/44540000/44549145.jpg',
      IsPrimary: false,
      IsVirtualSampleReady: false,
      Attributes: [],
      IsCustom: false,
      IsAvailable: false,
    },
  ],
  Attributes: [
    {
      Id: 811067021,
      Name: 'Less than Minimum',
      Description: 'Less than Minimum',
      Type: 'LMIN',
      Roles: [256],
      IsRequired: false,
      IsMultiSelect: false,
      Values: [
        {
          IsVisible: true,
          Sequence: 0,
          Id: 856970982,
          Value: 'Can order less than minimum',
          ValueGroup: 'Other',
          SetId: 811067021,
          Type: 'LMIN',
          Media: [],
          Charges: [],
          DisplaySequence: 1,
          SKU: [],
          CodedValue: 'Other',
        },
      ],
    },
    {
      Id: 811067026,
      Name: 'Standard & Numbered',
      Description: 'Standard & Numbered',
      Type: 'SIZE',
      Roles: [1, 2],
      IsRequired: false,
      IsMultiSelect: false,
      Values: [
        {
          IsVisible: true,
          Sequence: 0,
          Id: 856971143,
          Value: 'XS',
          ValueGroup: 'XS',
          SetId: 811067026,
          Type: 'SIZE',
          Media: [],
          Charges: [],
          PriceGridId: 848173794,
          DisplaySequence: 1,
          SKU: [
            '0DT8000BLHTXS',
            '0DT8000BLKXS',
            '0DT8000CHTXS',
            '0DT8000DPBHXS',
            '0DT8000HTNYXS',
            '0DT8000LTHGXS',
            '0DT8000MAIYLXS',
            '0DT8000RUBRXS',
          ],
        },
        {
          IsVisible: true,
          Sequence: 1,
          Id: 856971142,
          Value: 'S',
          ValueGroup: 'S',
          SetId: 811067026,
          Type: 'SIZE',
          Media: [],
          Charges: [],
          PriceGridId: 848173794,
          DisplaySequence: 2,
          SKU: [
            '0DT8000BLHTS',
            '0DT8000BLKS',
            '0DT8000CHTS',
            '0DT8000DPBHS',
            '0DT8000HTNYS',
            '0DT8000LTHGS',
            '0DT8000MAIYLS',
            '0DT8000RUBRS',
          ],
        },
        {
          IsVisible: true,
          Sequence: 2,
          Id: 856971141,
          Value: 'M',
          ValueGroup: 'M',
          SetId: 811067026,
          Type: 'SIZE',
          Media: [],
          Charges: [],
          PriceGridId: 848173794,
          DisplaySequence: 3,
          SKU: [
            '0DT8000BLHTM',
            '0DT8000BLKM',
            '0DT8000CHTM',
            '0DT8000DPBHM',
            '0DT8000HTNYM',
            '0DT8000LTHGM',
            '0DT8000MAIYLM',
            '0DT8000RUBRM',
          ],
        },
        {
          IsVisible: true,
          Sequence: 3,
          Id: 856971140,
          Value: 'L',
          ValueGroup: 'L',
          SetId: 811067026,
          Type: 'SIZE',
          Media: [],
          Charges: [],
          PriceGridId: 848173794,
          DisplaySequence: 4,
          SKU: [
            '0DT8000BLHTL',
            '0DT8000BLKL',
            '0DT8000CHTL',
            '0DT8000DPBHL',
            '0DT8000HTNYL',
            '0DT8000LTHGL',
            '0DT8000MAIYLL',
            '0DT8000RUBRL',
          ],
        },
        {
          IsVisible: true,
          Sequence: 4,
          Id: 856971139,
          Value: 'XL',
          ValueGroup: 'XL',
          SetId: 811067026,
          Type: 'SIZE',
          Media: [],
          Charges: [],
          PriceGridId: 848173794,
          DisplaySequence: 5,
          SKU: [
            '0DT8000BLHTXL',
            '0DT8000BLKXL',
            '0DT8000CHTXL',
            '0DT8000DPBHXL',
            '0DT8000HTNYXL',
            '0DT8000LTHGXL',
            '0DT8000MAIYLXL',
            '0DT8000RUBRXL',
          ],
        },
        {
          IsVisible: true,
          Sequence: 5,
          Id: 856971138,
          Value: '2XL',
          ValueGroup: '2XL',
          SetId: 811067026,
          Type: 'SIZE',
          Media: [],
          Charges: [],
          PriceGridId: 848173795,
          DisplaySequence: 6,
          SKU: [
            '0DT8000BLHT2XL',
            '0DT8000BLK2XL',
            '0DT8000CHT2XL',
            '0DT8000DPBH2XL',
            '0DT8000HTNY2XL',
            '0DT8000LTHG2XL',
            '0DT8000MAIYL2XL',
            '0DT8000RUBR2XL',
          ],
        },
        {
          IsVisible: true,
          Sequence: 6,
          Id: 856971137,
          Value: '3XL',
          ValueGroup: '3XL',
          SetId: 811067026,
          Type: 'SIZE',
          Media: [],
          Charges: [],
          PriceGridId: 848173796,
          DisplaySequence: 7,
          SKU: [
            '0DT8000BLHT3XL',
            '0DT8000BLK3XL',
            '0DT8000CHT3XL',
            '0DT8000DPBH3XL',
            '0DT8000HTNY3XL',
            '0DT8000LTHG3XL',
            '0DT8000MAIYL3XL',
            '0DT8000RUBR3XL',
          ],
        },
        {
          IsVisible: true,
          Sequence: 7,
          Id: 856971136,
          Value: '4XL',
          ValueGroup: '4XL',
          SetId: 811067026,
          Type: 'SIZE',
          Media: [],
          Charges: [],
          PriceGridId: 848173797,
          DisplaySequence: 8,
          SKU: [
            '0DT8000BLHT4XL',
            '0DT8000BLK4XL',
            '0DT8000CHT4XL',
            '0DT8000DPBH4XL',
            '0DT8000HTNY4XL',
            '0DT8000LTHG4XL',
            '0DT8000MAIYL4XL',
            '0DT8000RUBR4XL',
          ],
        },
      ],
    },
  ],
  PriceGrids: [
    {
      IsVisible: true,
      Sequence: 0,
      Id: 1,
      Description: '',
      Prices: [
        {
          IsVisible: true,
          Sequence: 0,
          Price: 4.35,
          Cost: 2.61,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: { From: 75, To: 149 },
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 4.25,
          Cost: 2.55,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: { From: 150, To: 249 },
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 4.15,
          Cost: 2.49,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: { From: 250, To: 499 },
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 4.05,
          Cost: 2.43,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: { From: 500, To: 999 },
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 3.95,
          Cost: 2.37,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: { From: 1000, To: 2147483647 },
        },
      ],
      PriceIncludes: '1-color imprint on one side, two sides or full wrap.',
      UsageLevel: 'NONE',
      Attributes: [856971136, 856971137, 856971138, 856971139],
    },
    {
      IsVisible: false,
      Sequence: 0,
      Id: 2,
      Description: '',
      Prices: [
        {
          IsVisible: true,
          Sequence: 0,
          Price: 4.35,
          Cost: 2.61,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: { From: 75, To: 149 },
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 4.25,
          Cost: 2.55,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: { From: 150, To: 249 },
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 4.15,
          Cost: 2.49,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: { From: 250, To: 499 },
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 4.05,
          Cost: 2.43,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: { From: 500, To: 999 },
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 3.95,
          Cost: 2.37,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: { From: 1000, To: 2147483647 },
        },
      ],
      PriceIncludes: '1-color imprint on one side, two sides or full wrap.',
      UsageLevel: 'NONE',
      Attributes: [],
    },
  ],
  Charges: [],
  Currencies: [],
  Settings: {
    ShowProductColors: true,
    ShowProductSizes: true,
    ShowProductShape: true,
    ShowProductMaterial: true,
    ShowProductCPN: true,
    ShowProductImprintMethods: true,
    ShowProductPricing: true,
    ShowProductPriceGrids: true,
    ShowProductPriceRanges: true,
    ShowProductAdditionalCharges: true,
    ShowProductDiscount: true,
  },
};

export function mockPresentationProduct(
  recipe?: (product: PresentationProduct) => PresentationProduct
): PresentationProduct {
  const result = recipe
    ? produce(MOCK_PRESENTATION_PRODUCT, recipe)
    : MOCK_PRESENTATION_PRODUCT;

  return result as unknown as PresentationProduct;
}

export function mockPresentationProductColors(): PresentationProductAttribute {
  return {
    Id: 807791219,
    Name: 'Product Color',
    Description: 'Product Color',
    Type: 'PRCL',
    Roles: [1, 2],
    IsRequired: false,
    IsMultiSelect: false,
    Values: [
      {
        IsVisible: true,
        Sequence: 0,
        Id: 847144042,
        Value: 'Black',
        ValueGroup: 'Medium Black',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 1,
        SKU: [],
        CodedValue: 'Medium Black',
      },
      {
        IsVisible: true,
        Sequence: 1,
        Id: 847144041,
        Value: 'Cocoa Brown',
        ValueGroup: 'Medium Brown',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 2,
        SKU: [],
        CodedValue: 'Medium Brown',
      },
      {
        IsVisible: true,
        Sequence: 2,
        Id: 847144040,
        Value: 'Burgundy',
        ValueGroup: 'Dark Red',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 3,
        SKU: [],
        CodedValue: 'Dark Red',
      },
      {
        IsVisible: true,
        Sequence: 3,
        Id: 847144039,
        Value: 'Charcoal',
        ValueGroup: 'Dark Gray',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 4,
        SKU: [],
        CodedValue: 'Dark Gray',
      },
      {
        IsVisible: true,
        Sequence: 4,
        Id: 847144038,
        Value: 'Navy',
        ValueGroup: 'Dark Blue',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 5,
        SKU: [],
        CodedValue: 'Dark Blue',
      },
      {
        IsVisible: true,
        Sequence: 5,
        Id: 847144037,
        Value: 'Orange',
        ValueGroup: 'Medium Orange',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 6,
        SKU: [],
        CodedValue: 'Medium Orange',
      },
      {
        IsVisible: true,
        Sequence: 6,
        Id: 847144036,
        Value: 'Pink',
        ValueGroup: 'Medium Pink',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 7,
        SKU: [],
        CodedValue: 'Medium Pink',
      },
      {
        IsVisible: true,
        Sequence: 7,
        Id: 847144035,
        Value: 'Purple',
        ValueGroup: 'Medium Purple',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 8,
        SKU: [],
        CodedValue: 'Medium Purple',
      },
      {
        IsVisible: true,
        Sequence: 8,
        Id: 847144034,
        Value: 'Red',
        ValueGroup: 'Medium Red',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 9,
        SKU: [],
        CodedValue: 'Medium Red',
      },
      {
        IsVisible: true,
        Sequence: 9,
        Id: 847144033,
        Value: 'Royal Blue',
        ValueGroup: 'Bright Blue',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 10,
        SKU: [],
        CodedValue: 'Bright Blue',
      },
      {
        IsVisible: true,
        Sequence: 10,
        Id: 847144032,
        Value: 'Yellow',
        ValueGroup: 'Medium Yellow',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 11,
        SKU: [],
        CodedValue: 'Medium Yellow',
      },
      {
        IsVisible: true,
        Sequence: 11,
        Id: 847144031,
        Value: 'Camel',
        ValueGroup: 'Light Brown',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 12,
        SKU: [],
        CodedValue: 'Light Brown',
      },
      {
        IsVisible: true,
        Sequence: 12,
        Id: 847144030,
        Value: 'Forest Green',
        ValueGroup: 'Medium Green',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 13,
        SKU: [],
        CodedValue: 'Medium Green',
      },
      {
        IsVisible: true,
        Sequence: 13,
        Id: 847144029,
        Value: 'Heather',
        ValueGroup: 'Light Gray',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 14,
        SKU: [],
        CodedValue: 'Light Gray',
      },
      {
        IsVisible: true,
        Sequence: 14,
        Id: 847144028,
        Value: 'Cream',
        ValueGroup: 'DARK WHITE',
        SetId: 807791219,
        Type: 'PRCL',
        Media: [],
        Charges: [],
        DisplaySequence: 15,
        SKU: [],
        CodedValue: 'DARK WHITE',
      },
    ],
  };
}

export function mockPresentationPriceGrid(): PriceGrid[] {
  return [
    {
      IsVisible: true,
      Sequence: 0,
      Id: 846365465,
      Description: '',
      Prices: [
        {
          IsVisible: true,
          Sequence: 0,
          Price: 16.49,
          Cost: 9.894,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: {
            From: 24,
            To: 47,
          },
        },
        {
          IsVisible: true,
          Sequence: 1,
          Price: 16.23,
          Cost: 9.738,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: {
            From: 48,
            To: 143,
          },
        },
        {
          IsVisible: true,
          Sequence: 2,
          Price: 15.95,
          Cost: 9.57,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: {
            From: 144,
            To: 287,
          },
        },
        {
          IsVisible: true,
          Sequence: 3,
          Price: 15.68,
          Cost: 9.408,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: {
            From: 288,
            To: 575,
          },
        },
        {
          IsVisible: true,
          Sequence: 4,
          Price: 15.39,
          Cost: 9.234,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'USD',
          IsUndefined: false,
          Quantity: {
            From: 576,
            To: 2147483647,
          },
        },
      ],
      PriceIncludes: 'embroidery up to 5000 stitches.',
      UsageLevel: 'NONE',
      Attributes: [],
      AttributeMap: [],
      AttributeTypes: [],
      AttributeByTypes: {},
    },
  ];
}

export function mockPresentationMaterial(): PresentationProductAttribute {
  return {
    Id: 811005625,
    Name: 'Material',
    Description: 'Material',
    Type: 'MTRL',
    Roles: [1, 2],
    IsRequired: false,
    IsMultiSelect: false,
    Values: [
      {
        IsVisible: true,
        Sequence: 0,
        Id: 856712197,
        Value: 'Polycarbonate (Pc)',
        ValueGroup: 'Polycarbonate (PC)',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 1,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 1,
        Id: 856712196,
        Value: 'Pet/Pete',
        ValueGroup: 'PET/PETE',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 2,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 2,
        Id: 856712195,
        Value: 'Plastic Fdfdfd',
        ValueGroup: 'Other Plastic',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 3,
        SKU: [],
        CodedValue: 'Other Plastic',
      },
      {
        IsVisible: true,
        Sequence: 3,
        Id: 856712194,
        Value: 'Stainless Steel',
        ValueGroup: 'Stainless Steel',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 4,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 4,
        Id: 856712193,
        Value: 'Optical Glass - Updated Iupdated Iupdated',
        ValueGroup: 'Optical Glass',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 5,
        SKU: [],
        CodedValue: 'Optical Glass',
      },
      {
        IsVisible: true,
        Sequence: 5,
        Id: 856712192,
        Value: 'Aluminum',
        ValueGroup: 'Aluminum',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 6,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 6,
        Id: 856712191,
        Value: 'Abs',
        ValueGroup: 'ABS',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 7,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 7,
        Id: 856712190,
        Value: 'Nickel',
        ValueGroup: 'Nickel',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 8,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 8,
        Id: 856712189,
        Value: 'Suede',
        ValueGroup: 'Suede',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 9,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 9,
        Id: 856712188,
        Value: 'Hemp',
        ValueGroup: 'Hemp',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 10,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 10,
        Id: 856712187,
        Value: 'Optical Glass',
        ValueGroup: 'Optical Glass',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 11,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 11,
        Id: 856712186,
        Value: 'Polyester',
        ValueGroup: 'Polyester',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 12,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 12,
        Id: 856712185,
        Value: 'Acrylic',
        ValueGroup: 'Acrylic',
        SetId: 811005625,
        Type: 'MTRL',
        Media: [],
        Charges: [],
        DisplaySequence: 13,
        SKU: [],
      },
    ],
  };
}

export function mockPresentationShapes(): PresentationProductAttribute {
  return {
    Id: 811005623,
    Name: 'Shape',
    Description: 'Shape',
    Type: 'SHAP',
    Roles: [1, 2],
    IsRequired: false,
    IsMultiSelect: false,
    Values: [
      {
        IsVisible: true,
        Sequence: 0,
        Id: 856712169,
        Value: 'Custom Shapes',
        ValueGroup: 'Custom Shapes',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 1,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 1,
        Id: 856712168,
        Value: 'Any Shape',
        ValueGroup: 'Any Shape',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 2,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 2,
        Id: 856712167,
        Value: 'Walnut',
        ValueGroup: 'Walnut',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 3,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 3,
        Id: 856712166,
        Value: 'Ear',
        ValueGroup: 'Ear',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 4,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 4,
        Id: 856712165,
        Value: 'Racquet',
        ValueGroup: 'Racquet',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 5,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 5,
        Id: 856712164,
        Value: 'Tape Measure',
        ValueGroup: 'Tape Measure',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 6,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 6,
        Id: 856712163,
        Value: 'Tank',
        ValueGroup: 'Tank',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 7,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 7,
        Id: 856712162,
        Value: 'Walkie Talkie',
        ValueGroup: 'Walkie Talkie',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 8,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 8,
        Id: 856712161,
        Value: 'Race Car',
        ValueGroup: 'Race Car',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 9,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 9,
        Id: 856712160,
        Value: 'I Heart U',
        ValueGroup: 'I Heart U',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 10,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 10,
        Id: 856712159,
        Value: 'U.S.A.',
        ValueGroup: 'U.S.A.',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 11,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 11,
        Id: 856712158,
        Value: 'Yacht',
        ValueGroup: 'Yacht',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 12,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 12,
        Id: 856712157,
        Value: 'Talon Hand',
        ValueGroup: 'Talon Hand',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 13,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 13,
        Id: 856712156,
        Value: 'Raccoon',
        ValueGroup: 'Raccoon',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 14,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 14,
        Id: 856712155,
        Value: 'Eagle',
        ValueGroup: 'Eagle',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 15,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 15,
        Id: 856712154,
        Value: 'Quill',
        ValueGroup: 'Quill',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 16,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 16,
        Id: 856712153,
        Value: 'Question Mark',
        ValueGroup: 'Question Mark',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 17,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 17,
        Id: 856712152,
        Value: 'Waiter / Waitress',
        ValueGroup: 'Waiter / Waitress',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 18,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 18,
        Id: 856712151,
        Value: 'Wagon',
        ValueGroup: 'Wagon',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 19,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 19,
        Id: 856712150,
        Value: 'T-Shirt',
        ValueGroup: 'T-Shirt',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 20,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 20,
        Id: 856712149,
        Value: 'Taco',
        ValueGroup: 'Taco',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 21,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 21,
        Id: 856712148,
        Value: 'Round',
        ValueGroup: 'Round',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 22,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 22,
        Id: 856712147,
        Value: 'Square',
        ValueGroup: 'Square',
        SetId: 811005623,
        Type: 'SHAP',
        Media: [],
        Charges: [],
        DisplaySequence: 23,
        SKU: [],
      },
    ],
  };
}

export function mockPresentationSize(): PresentationProductAttribute {
  return {
    Id: 811005624,
    Name: 'Apparel-Infant/Toddler (3 Months, 2T)',
    Description: 'Apparel-Infant/Toddler (3 Months, 2T)',
    Type: 'SIZE',
    Roles: [1, 2],
    IsRequired: false,
    IsMultiSelect: false,
    Values: [
      {
        IsVisible: true,
        Sequence: 0,
        Id: 856712184,
        Value: '0-3 months',
        ValueGroup: '0-3 months',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 1,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 1,
        Id: 856712183,
        Value: '3-6 months',
        ValueGroup: '3-6 months',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 2,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 2,
        Id: 856712182,
        Value: '6-12 months',
        ValueGroup: '6-12 months',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 3,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 3,
        Id: 856712181,
        Value: '12-18 months',
        ValueGroup: '12-18 months',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 4,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 4,
        Id: 856712180,
        Value: '18-24 months',
        ValueGroup: '18-24 months',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 5,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 5,
        Id: 856712179,
        Value: 'Newborn',
        ValueGroup: 'Newborn',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 6,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 6,
        Id: 856712178,
        Value: '3 months',
        ValueGroup: '3 months',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 7,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 7,
        Id: 856712177,
        Value: '6 months',
        ValueGroup: '6 months',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 8,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 8,
        Id: 856712176,
        Value: '12 months',
        ValueGroup: '12 months',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 9,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 9,
        Id: 856712175,
        Value: '24 months',
        ValueGroup: '24 months',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 10,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 10,
        Id: 856712174,
        Value: '2T',
        ValueGroup: '2T',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 11,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 11,
        Id: 856712173,
        Value: '3T',
        ValueGroup: '3T',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 12,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 12,
        Id: 856712172,
        Value: '4T',
        ValueGroup: '4T',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 13,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 13,
        Id: 856712171,
        Value: '5T',
        ValueGroup: '5T',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 14,
        SKU: [],
      },
      {
        IsVisible: true,
        Sequence: 14,
        Id: 856712170,
        Value: '6T',
        ValueGroup: '6T',
        SetId: 811005624,
        Type: 'SIZE',
        Media: [],
        Charges: [],
        DisplaySequence: 15,
        SKU: [],
      },
    ],
  };
}

export function mockProductForAttributeHidden(): Partial<PresentationProduct> {
  return {
    ...MOCK_PRESENTATION_PRODUCT,
    Attributes: [
      {
        Id: 68889161,
        Name: 'Material',
        Description: 'M',
        Type: 'MTRL',
        Roles: [1, 2],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: false,
            Sequence: 0,
            Id: 754624565,
            Value: 'Acrylic',
            ValueGroup: 'Other',
            SetId: 68889161,
            Type: 'MTRL',
            Media: [],
            Charges: [],
            SKU: [],
            CodedValue: 'Other',
          },
        ],
      },
      {
        Id: 68889162,
        Name: 'Imprint Method',
        Description: 'M',
        Type: 'IMMD',
        Roles: [3],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 769611274,
            Value: 'Embroidery',
            ValueGroup: 'Embroidered',
            SetId: 68889162,
            Type: 'IMMD',
            Media: [],
            Charges: [838045641, 823821839],
            PriceGridId: 837284778,
            SKU: [],
            CodedValue: 'Embroidered',
          },
          {
            IsVisible: true,
            Sequence: 1,
            Id: 774580612,
            Value: 'Unimprinted',
            ValueGroup: 'Unimprinted',
            SetId: 68889162,
            Type: 'IMMD',
            Media: [],
            Charges: [],
            PriceGridId: 837284777,
            DisplaySequence: 1,
            SKU: [],
          },
          {
            IsVisible: true,
            Sequence: 2,
            Id: 829835770,
            Value: 'Applique',
            ValueGroup: 'Other',
            SetId: 68889162,
            Type: 'IMMD',
            Media: [],
            Charges: [],
            PriceGridId: 837284778,
            DisplaySequence: 5,
            SKU: [],
            CodedValue: 'Other',
          },
        ],
      },
      {
        Id: 68889163,
        Name: 'Product Color',
        Description: 'C',
        Type: 'PRCL',
        Roles: [1, 2],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: false,
            Sequence: 0,
            Id: 127139329,
            Value: 'Black (995)',
            ValueGroup: 'Medium Black',
            SetId: 68889163,
            Type: 'PRCL',
            Media: [],
            Charges: [],
            DisplaySequence: 1,
            SKU: [],
            CodedValue: 'Medium Black',
          },
          {
            IsVisible: false,
            Sequence: 1,
            Id: 127139330,
            Value: 'Winter White (127)',
            ValueGroup: 'Medium White',
            SetId: 68889163,
            Type: 'PRCL',
            Media: [],
            Charges: [],
            DisplaySequence: 2,
            SKU: [],
            CodedValue: 'Medium White',
          },
          {
            IsVisible: false,
            Sequence: 2,
            Id: 127139331,
            Value: 'Vintage Red (369)',
            ValueGroup: 'Medium Red',
            SetId: 68889163,
            Type: 'PRCL',
            Media: [],
            Charges: [],
            DisplaySequence: 3,
            SKU: [],
            CodedValue: 'Medium Red',
          },
          {
            IsVisible: false,
            Sequence: 3,
            Id: 127139332,
            Value: 'Nautical (572)',
            ValueGroup: 'Medium Blue',
            SetId: 68889163,
            Type: 'PRCL',
            Media: [],
            Charges: [],
            DisplaySequence: 4,
            SKU: [],
            CodedValue: 'Medium Blue',
          },
          {
            IsVisible: false,
            Sequence: 4,
            Id: 754624566,
            Value: 'Charcoal (990)',
            ValueGroup: 'Medium Gray',
            SetId: 68889163,
            Type: 'PRCL',
            Media: [],
            Charges: [],
            DisplaySequence: 5,
            SKU: [],
            CodedValue: 'Medium Gray',
          },
        ],
      },
      {
        Id: 68889167,
        Name: 'FOB Point',
        Description: 'FOBS',
        Type: 'FOBP',
        Roles: [5],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 754624422,
            Value: 'Richmond Hill,  ON L4B 4W3 Canada',
            ValueGroup: 'Richmond Hill,  ON L4B 4W3 Canada',
            SetId: 68889167,
            Type: 'FOBP',
            Media: [],
            Charges: [],
            DisplaySequence: 0,
            SKU: [],
          },
        ],
      },
      {
        Id: 499753980,
        Name: 'Rush Service',
        Description: 'Rush Service',
        Type: 'RUSH',
        Roles: [4],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 747294392,
            Value: 'Rush Service',
            ValueGroup: 'Other',
            SetId: 499753980,
            Type: 'RUSH',
            Media: [],
            Charges: [825970330],
            SKU: [],
            CodedValue: 'Other',
          },
        ],
      },
      {
        Id: 766959609,
        Name: 'Standard & Numbered',
        Description: 'Size',
        Type: 'SIZE',
        Roles: [1, 2],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 127139325,
            Value: 'One Size',
            ValueGroup: 'One Size',
            SetId: 766959609,
            Type: 'SIZE',
            Media: [],
            Charges: [],
            DisplaySequence: 1,
            SKU: [],
          },
        ],
      },
      {
        Id: 777116717,
        Name: 'Drop/Split Shipments Available',
        Type: 'SHOP',
        Roles: [5, 4],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 769611012,
            Value: 'Drop/Split Shipments',
            ValueGroup: 'Other',
            SetId: 777116717,
            Type: 'SHOP',
            Media: [],
            Charges: [823820974],
            DisplaySequence: 1,
            SKU: [],
            CodedValue: 'Other',
          },
        ],
      },
      {
        Id: 777116736,
        Name: 'Custom Non Standard Packing Available',
        Type: 'SHOP',
        Roles: [5, 4],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 769611045,
            Value: 'Custom Non Standard Packing',
            ValueGroup: 'Other',
            SetId: 777116736,
            Type: 'SHOP',
            Media: [],
            Charges: [823821024],
            DisplaySequence: 1,
            SKU: [],
            CodedValue: 'Other',
          },
        ],
      },
      {
        Id: 777116753,
        Name: 'Other Charges',
        Type: 'PROP',
        Roles: [4],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 769611084,
            Value: 'Attach Customer Supplied Tags',
            ValueGroup: 'Other',
            SetId: 777116753,
            Type: 'PROP',
            Media: [],
            Charges: [823821162],
            DisplaySequence: 1,
            SKU: [],
            CodedValue: 'Other',
          },
          {
            IsVisible: true,
            Sequence: 1,
            Id: 769611083,
            Value: 'Attach Customer Barcode Labels',
            ValueGroup: 'Other',
            SetId: 777116753,
            Type: 'PROP',
            Media: [],
            Charges: [823821163],
            DisplaySequence: 2,
            SKU: [],
            CodedValue: 'Other',
          },
        ],
      },
      {
        Id: 777117291,
        Name: 'Artwork & Proofs',
        Description: 'Artwork & Proofs',
        Type: 'ARTW',
        Roles: [3],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 769612816,
            Value: 'Art Services',
            ValueGroup: 'Art Services',
            SetId: 777117291,
            Type: 'ARTW',
            Media: [],
            Charges: [823822111],
            DisplaySequence: 1,
            SKU: [],
          },
          {
            IsVisible: true,
            Sequence: 1,
            Id: 769612817,
            Value: 'Paper Proof',
            ValueGroup: 'Paper Proof',
            Description: 'No charge for first proof.',
            SetId: 777117291,
            Type: 'ARTW',
            Media: [],
            Charges: [823822112],
            DisplaySequence: 2,
            SKU: [],
          },
          {
            IsVisible: true,
            Sequence: 2,
            Id: 769612819,
            Value: 'Virtual Proof',
            ValueGroup: 'Virtual Proof',
            Description: 'Virtual mock up.',
            SetId: 777117291,
            Type: 'ARTW',
            Media: [],
            Charges: [823822113],
            DisplaySequence: 3,
            SKU: [],
          },
          {
            IsVisible: true,
            Sequence: 3,
            Id: 769612818,
            Value: 'Storyboards',
            ValueGroup: 'Other',
            Description: 'Storyboards',
            SetId: 777117291,
            Type: 'ARTW',
            Media: [],
            Charges: [823822114],
            DisplaySequence: 4,
            SKU: [],
            CodedValue: 'Other',
          },
        ],
      },
      {
        Id: 777118430,
        Name: 'Less than Minimum',
        Description: 'Less than Minimum',
        Type: 'LMIN',
        Roles: [4],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 769616828,
            Value: 'Can order less than minimum',
            ValueGroup: 'Other',
            SetId: 777118430,
            Type: 'LMIN',
            Media: [],
            Charges: [823826431],
            SKU: [],
            CodedValue: 'Other',
          },
        ],
      },
      {
        Id: 791822555,
        Name: 'Packaging',
        Description: 'Packaging',
        Type: 'PCKG',
        Roles: [256],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 802999593,
            Value: 'Folding and polybagging',
            ValueGroup: 'Custom',
            SetId: 791822555,
            Type: 'PCKG',
            Media: [],
            Charges: [],
            DisplaySequence: 0,
            SKU: [],
            CodedValue: 'Custom',
          },
        ],
      },
      {
        Id: 791822560,
        Name: 'Imprint Option',
        Description: 'Samples',
        Type: 'SMPL',
        Roles: [4],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 802999599,
            Value: 'Spec Sample',
            ValueGroup: 'Spec Sample',
            SetId: 791822560,
            Type: 'SMPL',
            Media: [],
            Charges: [838045748],
            DisplaySequence: 7,
            SKU: [],
          },
          {
            IsVisible: true,
            Sequence: 1,
            Id: 802999598,
            Value: 'Product Sample',
            ValueGroup: 'Product Sample',
            SetId: 791822560,
            Type: 'SMPL',
            Media: [],
            Charges: [838045748],
            DisplaySequence: 8,
            SKU: [],
          },
        ],
      },
      {
        Id: 791896404,
        Name: 'Embroidery options',
        Type: 'IMOP',
        Roles: [3],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 803106343,
            Value: '10001 stitches and up; per 5000 stitches',
            ValueGroup: 'Other',
            SetId: 791896404,
            Type: 'IMOP',
            Media: [],
            Charges: [838045684],
            DisplaySequence: 1,
            SKU: [],
            CodedValue: 'Other',
          },
          {
            IsVisible: true,
            Sequence: 1,
            Id: 803106401,
            Value: '3D (Puff) Embroidery',
            ValueGroup: 'Other',
            SetId: 791896404,
            Type: 'IMOP',
            Media: [],
            Charges: [838045685],
            DisplaySequence: 2,
            SKU: [],
            CodedValue: 'Other',
          },
          {
            IsVisible: true,
            Sequence: 2,
            Id: 803106385,
            Value: 'Personalization and type',
            ValueGroup: 'Other',
            SetId: 791896404,
            Type: 'IMOP',
            Media: [],
            Charges: [838045686],
            DisplaySequence: 3,
            SKU: [],
            CodedValue: 'Other',
          },
          {
            IsVisible: true,
            Sequence: 3,
            Id: 803106344,
            Value: 'Metallic thread',
            ValueGroup: 'Other',
            SetId: 791896404,
            Type: 'IMOP',
            Media: [],
            Charges: [838045687],
            DisplaySequence: 4,
            SKU: [],
            CodedValue: 'Other',
          },
          {
            IsVisible: true,
            Sequence: 4,
            Id: 803106386,
            Value: 'Edit DST files/typeset (standard fonts)',
            ValueGroup: 'Other',
            SetId: 791896404,
            Type: 'IMOP',
            Media: [],
            Charges: [838045688],
            DisplaySequence: 5,
            SKU: [],
            CodedValue: 'Other',
          },
        ],
      },
      {
        Id: 804996330,
        Name: 'Imprint Color',
        Description: 'Imprint Color',
        Type: 'IMCL',
        Roles: [3],
        IsRequired: false,
        IsMultiSelect: false,
        Values: [
          {
            IsVisible: true,
            Sequence: 0,
            Id: 838944444,
            Value: 'Standard',
            ValueGroup: 'Other',
            SetId: 804996330,
            Type: 'IMCL',
            Media: [],
            Charges: [],
            DisplaySequence: 0,
            SKU: [],
            CodedValue: 'Other',
          },
        ],
      },
    ],
  };
}

export function mockPriceGridForAttributeHidden(): PriceGrid[] {
  return [
    {
      IsVisible: true,
      Sequence: 0,
      Id: 837284777,
      Description: 'Blank',
      Prices: [
        {
          IsVisible: true,
          Sequence: 0,
          Price: 10.8,
          Cost: 5.4,
          DiscountCode: 'P',
          DiscountPercent: 0.5,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 200,
            To: 200,
          },
        },
        {
          IsVisible: true,
          Sequence: 1,
          Price: 10.4,
          Cost: 5.2,
          DiscountCode: 'P',
          DiscountPercent: 0.5,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 100,
            To: 224,
          },
        },
        {
          IsVisible: true,
          Sequence: 2,
          Price: 8.95,
          Cost: 4.922,
          DiscountCode: 'Q',
          DiscountPercent: 0.45,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 50,
            To: 50,
          },
        },
        {
          IsVisible: true,
          Sequence: 3,
          Price: 7.7,
          Cost: 4.62,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 500,
            To: 500,
          },
        },
        {
          IsVisible: true,
          Sequence: 4,
          Price: 7.1,
          Cost: 4.26,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 300,
            To: 300,
          },
        },
      ],
      PriceIncludes: 'blank product.',
      UsageLevel: 'NONE',
      Attributes: [774580612],
      AttributeMap: [
        {
          IsVisible: true,
          Sequence: 1,
          Id: 774580612,
          Value: 'Unimprinted',
          ValueGroup: 'Unimprinted',
          SetId: 68889162,
          Type: 'IMMD',
          Media: [],
          Charges: [],
          PriceGridId: 837284777,
          DisplaySequence: 1,
          SKU: [],
          Name: 'Imprint Method',
        },
      ],
      AttributeTypes: ['IMMD'],
      AttributeByTypes: {
        IMMD: {
          Name: 'Imprint Method',
          Type: 'IMMD',
          Values: [
            {
              IsVisible: true,
              Sequence: 1,
              Id: 774580612,
              Value: 'Unimprinted',
              ValueGroup: 'Unimprinted',
              SetId: 68889162,
              Type: 'IMMD',
              Media: [],
              Charges: [],
              PriceGridId: 837284777,
              DisplaySequence: 1,
              SKU: [],
              Name: 'Imprint Method',
            },
          ],
        },
      },
    },
    {
      IsVisible: true,
      Sequence: 1,
      Id: 837284778,
      Description: 'Decorated',
      Prices: [
        {
          IsVisible: true,
          Sequence: 0,
          Price: 17.3,
          Cost: 8.65,
          DiscountCode: 'P',
          DiscountPercent: 0.5,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 24,
            To: 99,
          },
        },
        {
          IsVisible: true,
          Sequence: 1,
          Price: 16.75,
          Cost: 8.375,
          DiscountCode: 'P',
          DiscountPercent: 0.5,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 100,
            To: 224,
          },
        },
        {
          IsVisible: true,
          Sequence: 2,
          Price: 14.55,
          Cost: 8.002,
          DiscountCode: 'Q',
          DiscountPercent: 0.45,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 225,
            To: 374,
          },
        },
        {
          IsVisible: true,
          Sequence: 3,
          Price: 12.7,
          Cost: 7.62,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 375,
            To: 499,
          },
        },
        {
          IsVisible: true,
          Sequence: 4,
          Price: 12,
          Cost: 7.2,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 500,
            To: 2147483647,
          },
        },
      ],
      PriceIncludes: 'first location run charges.',
      UsageLevel: 'NONE',
      Attributes: [829835770, 769611274],
      AttributeMap: [
        {
          IsVisible: true,
          Sequence: 2,
          Id: 829835770,
          Value: 'Applique',
          ValueGroup: 'Other',
          SetId: 68889162,
          Type: 'IMMD',
          Media: [],
          Charges: [],
          PriceGridId: 837284778,
          DisplaySequence: 5,
          SKU: [],
          CodedValue: 'Other',
          Name: 'Imprint Method',
        },
        {
          IsVisible: true,
          Sequence: 0,
          Id: 769611274,
          Value: 'Embroidery',
          ValueGroup: 'Embroidered',
          SetId: 68889162,
          Type: 'IMMD',
          Media: [],
          Charges: [838045641, 823821839],
          PriceGridId: 837284778,
          SKU: [],
          CodedValue: 'Embroidered',
          Name: 'Imprint Method',
        },
      ],
      AttributeTypes: ['IMMD'],
      AttributeByTypes: {
        IMMD: {
          Name: 'Imprint Method',
          Type: 'IMMD',
          Values: [
            {
              IsVisible: true,
              Sequence: 2,
              Id: 829835770,
              Value: 'Applique',
              ValueGroup: 'Other',
              SetId: 68889162,
              Type: 'IMMD',
              Media: [],
              Charges: [],
              PriceGridId: 837284778,
              DisplaySequence: 5,
              SKU: [],
              CodedValue: 'Other',
              Name: 'Imprint Method',
            },
            {
              IsVisible: true,
              Sequence: 0,
              Id: 769611274,
              Value: 'Embroidery',
              ValueGroup: 'Embroidered',
              SetId: 68889162,
              Type: 'IMMD',
              Media: [],
              Charges: [838045641, 823821839],
              PriceGridId: 837284778,
              SKU: [],
              CodedValue: 'Embroidered',
              Name: 'Imprint Method',
            },
          ],
        },
      },
    },
  ];
}

export function mockInvisiblePriceGrid(): PriceGrid[] {
  return [
    {
      IsVisible: false,
      Sequence: 0,
      Id: 837284777,
      Description: 'Blank',
      Prices: [
        {
          IsVisible: true,
          Sequence: 2,
          Price: 8.95,
          Cost: 4.922,
          DiscountCode: 'Q',
          DiscountPercent: 0.45,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 50,
            To: 50,
          },
        },
        {
          IsVisible: true,
          Sequence: 1,
          Price: 10.4,
          Cost: 5.2,
          DiscountCode: 'P',
          DiscountPercent: 0.5,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 100,
            To: 224,
          },
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 10.8,
          Cost: 5.4,
          DiscountCode: 'P',
          DiscountPercent: 0.5,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 200,
            To: 200,
          },
        },
        {
          IsVisible: true,
          Sequence: 4,
          Price: 7.1,
          Cost: 4.26,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 300,
            To: 300,
          },
        },
        {
          IsVisible: true,
          Sequence: 3,
          Price: 7.7,
          Cost: 4.62,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 500,
            To: 500,
          },
        },
      ],
      PriceIncludes: 'blank product.',
      UsageLevel: 'NONE',
      Attributes: [774580612],
      AttributeTypes: ['IMMD'],
      AttributeByTypes: {
        IMMD: {
          Name: 'Imprint Method',
          Type: 'IMMD',
          Values: [{ Value: 'Unimprinted', Type: 'IMMD', Id: 774580612 }],
        },
      } as Record<string, { Name: string; Type: string }>,
    },
    {
      IsVisible: false,
      Sequence: 1,
      Id: 837284778,
      Description: 'Decorated',
      Prices: [
        {
          IsVisible: true,
          Sequence: 0,
          Price: 17.3,
          Cost: 8.65,
          DiscountCode: 'P',
          DiscountPercent: 0.5,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 24,
            To: 99,
          },
        },
        {
          IsVisible: true,
          Sequence: 1,
          Price: 16.75,
          Cost: 8.375,
          DiscountCode: 'P',
          DiscountPercent: 0.5,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 100,
            To: 224,
          },
        },
        {
          IsVisible: true,
          Sequence: 2,
          Price: 14.55,
          Cost: 8.002,
          DiscountCode: 'Q',
          DiscountPercent: 0.45,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 225,
            To: 374,
          },
        },
        {
          IsVisible: true,
          Sequence: 3,
          Price: 12.7,
          Cost: 7.62,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 375,
            To: 499,
          },
        },
        {
          IsVisible: true,
          Sequence: 4,
          Price: 12,
          Cost: 7.2,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 500,
            To: 2147483647,
          },
        },
      ],
      PriceIncludes: 'first location run charges.',
      UsageLevel: 'NONE',
      Attributes: [829835770, 769611274],
      AttributeTypes: ['IMMD'],
      AttributeByTypes: {
        IMMD: {
          Name: 'Imprint Method',
          Type: 'IMMD',
          Values: [
            { Value: 'Embroidery', Type: 'IMMD', Id: 829835770 },
            { Value: 'Acrylic', Type: 'IMMD', Id: 769611274 },
          ],
        },
      } as Record<string, { Name: string; Type: string }>,
    },
  ] as PriceGrid[];
}

export function mockInvisiblePriceGridWithTwoAttributes(): PriceGrid[] {
  return [
    {
      IsVisible: false,
      Sequence: 0,
      Id: 837284777,
      Description: 'Blank',
      Prices: [
        {
          IsVisible: true,
          Sequence: 2,
          Price: 8.95,
          Cost: 4.922,
          DiscountCode: 'Q',
          DiscountPercent: 0.45,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 50,
            To: 50,
          },
        },
        {
          IsVisible: true,
          Sequence: 1,
          Price: 10.4,
          Cost: 5.2,
          DiscountCode: 'P',
          DiscountPercent: 0.5,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 100,
            To: 224,
          },
        },
        {
          IsVisible: true,
          Sequence: 0,
          Price: 10.8,
          Cost: 5.4,
          DiscountCode: 'P',
          DiscountPercent: 0.5,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 200,
            To: 200,
          },
        },
        {
          IsVisible: true,
          Sequence: 4,
          Price: 7.1,
          Cost: 4.26,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 300,
            To: 300,
          },
        },
        {
          IsVisible: true,
          Sequence: 3,
          Price: 7.7,
          Cost: 4.62,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 500,
            To: 500,
          },
        },
      ],
      PriceIncludes: 'blank product.',
      UsageLevel: 'NONE',
      Attributes: [829835770, 769611274, 856971143],
      AttributeTypes: ['IMMD', 'SIZE'],
      AttributeByTypes: {
        IMMD: {
          Name: 'Imprint Method',
          Type: 'IMMD',
          Values: [
            { Value: 'Embroidery', Type: 'IMMD', Id: 829835770 },
            { Value: 'Acrylic', Type: 'IMMD', Id: 769611274 },
          ],
        },
        SIZE: {
          Name: 'Standard & Numbered',
          Type: 'SIZE',
          Values: [{ Value: 'XS', Type: 'SIZE', Id: 856971143 }],
        },
      } as Record<string, { Name: string; Type: string }>,
    },
    {
      IsVisible: false,
      Sequence: 1,
      Id: 837284778,
      Description: 'Decorated',
      Prices: [
        {
          IsVisible: true,
          Sequence: 0,
          Price: 17.3,
          Cost: 8.65,
          DiscountCode: 'P',
          DiscountPercent: 0.5,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 24,
            To: 99,
          },
        },
        {
          IsVisible: true,
          Sequence: 1,
          Price: 16.75,
          Cost: 8.375,
          DiscountCode: 'P',
          DiscountPercent: 0.5,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 100,
            To: 224,
          },
        },
        {
          IsVisible: true,
          Sequence: 2,
          Price: 14.55,
          Cost: 8.002,
          DiscountCode: 'Q',
          DiscountPercent: 0.45,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 225,
            To: 374,
          },
        },
        {
          IsVisible: true,
          Sequence: 3,
          Price: 12.7,
          Cost: 7.62,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 375,
            To: 499,
          },
        },
        {
          IsVisible: true,
          Sequence: 4,
          Price: 12,
          Cost: 7.2,
          DiscountCode: 'R',
          DiscountPercent: 0.4,
          CurrencyCode: 'CAD',
          IsUndefined: false,
          Quantity: {
            From: 500,
            To: 2147483647,
          },
        },
      ],
      PriceIncludes: 'first location run charges.',
      UsageLevel: 'NONE',
      Attributes: [829835770, 769611274, 856971143],
      AttributeTypes: ['IMMD', 'SIZE'],
      AttributeByTypes: {
        IMMD: {
          Name: 'Imprint Method',
          Type: 'IMMD',
          Values: [
            { Value: 'Embroidery', Type: 'IMMD', Id: 829835770 },
            { Value: 'Acrylic', Type: 'IMMD', Id: 769611274 },
          ],
        },
        SIZE: {
          Name: 'Standard & Numbered',
          Type: 'SIZE',
          Values: [{ Value: 'XS', Type: 'SIZE', Id: 856971143 }],
        },
      } as Record<string, { Name: string; Type: string }>,
    },
  ] as PriceGrid[];
}
export function mockInvisiblePriceGridWithQUR(): PriceGrid[] {
  return [
    {
      IsVisible: false,
      Sequence: 0,
      Id: 837284777,
      Description: 'Blank',
      Prices: [
        {
          IsVisible: true,
          Sequence: 2,
          Price: 0,
          Cost: 0,
          DiscountCode: 'Q',
          DiscountPercent: 0,
          CurrencyCode: 'CAD',
          IsUndefined: true,
          Quantity: {
            From: 50,
            To: 50,
          },
        },
      ],
      PriceIncludes: 'blank product.',
      UsageLevel: 'NONE',
      Attributes: [774580612],
      AttributeTypes: ['IMMD'],
      AttributeByTypes: {
        IMMD: {
          Name: 'Imprint Method',
          Type: 'IMMD',
          Values: [{ Value: 'Unimprinted', Type: 'IMMD', Id: 774580612 }],
        },
      } as Record<string, { Name: string; Type: string }>,
    },
    {
      IsVisible: false,
      Sequence: 1,
      Id: 837284778,
      Description: 'Decorated',
      Prices: [
        {
          IsVisible: true,
          Sequence: 0,
          Price: 0,
          Cost: 0,
          DiscountCode: 'P',
          DiscountPercent: 0,
          CurrencyCode: 'CAD',
          IsUndefined: true,
          Quantity: {
            From: 24,
            To: 99,
          },
        },
      ],
      PriceIncludes: 'first location run charges.',
      UsageLevel: 'NONE',
      Attributes: [829835770, 769611274],
      AttributeTypes: ['IMMD'],
      AttributeByTypes: {
        IMMD: {
          Name: 'Imprint Method',
          Type: 'IMMD',
          Values: [
            { Value: 'Embroidery', Type: 'IMMD', Id: 829835770 },
            { Value: 'Acrylic', Type: 'IMMD', Id: 769611274 },
          ],
        },
      } as Record<string, { Name: string; Type: string }>,
    },
  ] as PriceGrid[];
}
