export const MOCK_PRICES = [
  {
    IsVisible: true,
    Sequence: 0,
    Price: 4.35,
    Cost: 2.61,
    DiscountCode: 'R',
    DiscountPercent: 0.4,
    CurrencyCode: 'USD',
    IsUndefined: false,
    Quantity: { From: 75, To: 149 },
  },
  {
    IsVisible: true,
    Sequence: 0,
    Price: 4.25,
    Cost: 2.55,
    DiscountCode: 'R',
    DiscountPercent: 0.4,
    CurrencyCode: 'USD',
    IsUndefined: false,
    Quantity: { From: 150, To: 249 },
  },
  {
    IsVisible: true,
    Sequence: 0,
    Price: 4.15,
    Cost: 2.49,
    DiscountCode: 'R',
    DiscountPercent: 0.4,
    CurrencyCode: 'USD',
    IsUndefined: false,
    Quantity: { From: 250, To: 499 },
  },
  {
    IsVisible: true,
    Sequence: 0,
    Price: 4.05,
    Cost: 2.43,
    DiscountCode: 'R',
    DiscountPercent: 0.4,
    CurrencyCode: 'USD',
    IsUndefined: false,
    Quantity: { From: 500, To: 999 },
  },
  {
    IsVisible: true,
    Sequence: 0,
    Price: 3.95,
    Cost: 2.37,
    DiscountCode: 'R',
    DiscountPercent: 0.4,
    CurrencyCode: 'USD',
    IsUndefined: false,
    Quantity: { From: 1000, To: 2147483647 },
  },
];
