export const MOCK_QUOTE_PRODUCTS: any = [
  {
    Id: 504065188,
    CorrelationId: '5cbf238d-436d-454e-b613-dca4ade5a902',
    Type: 'product',
    Name: '22 5/8" 100% Polyester Adjustable Baseball Cap',
    Description:
      'This is adjustable polyester cap! Perfect for sports and live field,It is made of 100% polyester and features a medium profile, a structured crown, a pre-curved visor and an adjustable strap with a brass buckle to fit nearly everybody. It can be clasped in your pants or put in your pocket by folding. Very easy to carry when you travel. There is enough space to imprint your company name or logo. Perfect for publicity. Great idea to promotional events.',
    Relationships: [
      {
        Relationship: 'To Original',
        OrderId: 502188811,
        OrderNumber: '2023-12301063-Enc',
        LineItemId: 504065182,
      },
    ],
    Sequence: 0,
    CurrencyCode: 'USD',
    CurrencySymbol: '$',
    ConversionRate: 1,
    Totals: {
      Units: 88,
      Amount: 1143604,
      Cost: 511940,
      Margin: 631664,
      TaxableAmount: 1143604,
      SalesTax: 0,
      TaxRate: 0,
    },
    ConversionTotals: {
      Amount: 1143604,
      Cost: 511940,
      Margin: 631664,
      TaxableAmount: 1143604,
      SalesTax: 0,
      TaxRate: 0,
    },
    ProductId: 551238092,
    ImageUrl: 'https://media.asicdn.com/images/jpgt/25020000/25023297.jpg',
    Number: '018BBNGD',
    ShippingDetail: {
      Id: 505369217,
      From: {
        Id: 514516927,
        Name: 'BNS Promo Inc',
        Address: {
          Id: 0,
          Phone: {
            Id: 0,
            Type: 'Other',
            PhoneCode: '1',
            Country: 'US',
          },
          IsPrimary: false,
        },
        Company: {
          IsCompany: true,
          IsPerson: false,
          Id: 501254839,
          Name: 'BNS Promo Inc',
          Addresses: [],
          Phones: [
            {
              Id: 503202503,
              Type: 'Office',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(713) 261-8719',
              IsPrimary: true,
            },
          ],
          Emails: [
            {
              Id: 501519929,
              Address: 'support@bnspromo.com',
              IsPrimary: true,
              Type: 'Work',
            },
            {
              Id: 501519930,
              Address: 'artben@bnspromo.com',
              IsPrimary: false,
              Type: 'Artwork',
            },
            {
              Id: 501519931,
              Address: 'support@bnspromo.com',
              IsPrimary: false,
              Type: 'Order',
            },
          ],
          OwnerId: 178354,
          AccessLevel: 'Everyone',
          IsVisible: false,
          IsEditable: false,
        },
        Party: {
          IsCompany: true,
          IsPerson: false,
          Id: 501254839,
          Name: 'BNS Promo Inc',
          Addresses: [],
          Phones: [
            {
              Id: 503202503,
              Type: 'Office',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(713) 261-8719',
              IsPrimary: true,
            },
          ],
          Emails: [
            {
              Id: 501519929,
              Address: 'support@bnspromo.com',
              IsPrimary: true,
              Type: 'Work',
            },
            {
              Id: 501519930,
              Address: 'artben@bnspromo.com',
              IsPrimary: false,
              Type: 'Artwork',
            },
            {
              Id: 501519931,
              Address: 'support@bnspromo.com',
              IsPrimary: false,
              Type: 'Order',
            },
          ],
          OwnerId: 178354,
          AccessLevel: 'Everyone',
          IsVisible: false,
          IsEditable: false,
        },
      },
      To: {
        Id: 514516928,
        Name: 'ASI Garments :P ;)',
        Address: {
          Id: 0,
          Line1: '4800 Street Rd',
          City: 'Feasterville-Trevose',
          State: 'PA',
          PostalCode: '236236',
          Country: 'United States',
          CountryType: 'US',
          Phone: {
            Id: 0,
            Type: 'Office',
            PhoneCode: '1',
            Country: 'US',
            Number: '123456789',
            Extension: '',
          },
          IsPrimary: true,
        },
        Company: {
          IsCompany: true,
          IsPerson: false,
          Id: 513543216,
          Name: 'ASI Garments :P ;)',
          Addresses: [
            {
              Id: 506710964,
              Name: 'ASI Garments :P ;)',
              Line1: '1003 Hamilton Blvd NE',
              City: 'Airdrie',
              County: '',
              State: 'AB',
              PostalCode: 'T4A 0R1',
              Country: 'Canada',
              CountryType: 'CA',
              IsPrimary: true,
              Type: 'GNRL',
            },
          ],
          Phones: [
            {
              Id: 510416200,
              Type: 'Office',
              PhoneCode: '1',
              Country: 'CA',
              Number: '123456789',
              IsPrimary: true,
              Extension: '',
            },
          ],
          Emails: [
            {
              Id: 508593750,
              Address: 'example@email.com',
              IsPrimary: true,
              Type: 'Work',
            },
          ],
          IconMediaLink: {
            Id: 0,
            MediaId: 5707865,
            FileUrl:
              'https://commonmedia.uat-asicentral.com/orders/Artwork/8ede0e38272a45b09e0dc85941bec2a9.png',
            DownloadFileUrl:
              'https://commonmedia.uat-asicentral.com/orders/Artwork/8ede0e38272a45b09e0dc85941bec2a9.png',
            IsVisible: false,
            FileSize: 0,
          },
          OwnerId: 553138,
          AccessLevel: 'Everyone',
          IsVisible: true,
          IsEditable: true,
        },
      },
      IsInHandsDateFlexible: false,
      CarrierName: '',
      ShippingAccountVisible: false,
      IsBlindShip: false,
      Sequence: 1,
    },
    ShippingDetails: [
      {
        Id: 505369217,
        From: {
          Id: 514516927,
          Name: 'BNS Promo Inc',
          Address: {
            Id: 0,
            Phone: {
              Id: 0,
              Type: 'Other',
              PhoneCode: '1',
              Country: 'US',
            },
            IsPrimary: false,
          },
          Company: {
            IsCompany: true,
            IsPerson: false,
            Id: 501254839,
            Name: 'BNS Promo Inc',
            Addresses: [],
            Phones: [
              {
                Id: 503202503,
                Type: 'Office',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(713) 261-8719',
                IsPrimary: true,
              },
            ],
            Emails: [
              {
                Id: 501519929,
                Address: 'support@bnspromo.com',
                IsPrimary: true,
                Type: 'Work',
              },
              {
                Id: 501519930,
                Address: 'artben@bnspromo.com',
                IsPrimary: false,
                Type: 'Artwork',
              },
              {
                Id: 501519931,
                Address: 'support@bnspromo.com',
                IsPrimary: false,
                Type: 'Order',
              },
            ],
            OwnerId: 178354,
            AccessLevel: 'Everyone',
            IsVisible: false,
            IsEditable: false,
          },
          Party: {
            IsCompany: true,
            IsPerson: false,
            Id: 501254839,
            Name: 'BNS Promo Inc',
            Addresses: [],
            Phones: [
              {
                Id: 503202503,
                Type: 'Office',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(713) 261-8719',
                IsPrimary: true,
              },
            ],
            Emails: [
              {
                Id: 501519929,
                Address: 'support@bnspromo.com',
                IsPrimary: true,
                Type: 'Work',
              },
              {
                Id: 501519930,
                Address: 'artben@bnspromo.com',
                IsPrimary: false,
                Type: 'Artwork',
              },
              {
                Id: 501519931,
                Address: 'support@bnspromo.com',
                IsPrimary: false,
                Type: 'Order',
              },
            ],
            OwnerId: 178354,
            AccessLevel: 'Everyone',
            IsVisible: false,
            IsEditable: false,
          },
        },
        To: {
          Id: 514516928,
          Name: 'ASI Garments :P ;)',
          Address: {
            Id: 0,
            Line1: '4800 Street Rd',
            City: 'Feasterville-Trevose',
            State: 'PA',
            PostalCode: '236236',
            Country: 'United States',
            CountryType: 'US',
            Phone: {
              Id: 0,
              Type: 'Office',
              PhoneCode: '1',
              Country: 'US',
              Number: '123456789',
              Extension: '',
            },
            IsPrimary: true,
          },
          Company: {
            IsCompany: true,
            IsPerson: false,
            Id: 513543216,
            Name: 'ASI Garments :P ;)',
            Addresses: [
              {
                Id: 506710964,
                Name: 'ASI Garments :P ;)',
                Line1: '1003 Hamilton Blvd NE',
                City: 'Airdrie',
                County: '',
                State: 'AB',
                PostalCode: 'T4A 0R1',
                Country: 'Canada',
                CountryType: 'CA',
                IsPrimary: true,
                Type: 'GNRL',
              },
            ],
            Phones: [
              {
                Id: 510416200,
                Type: 'Office',
                PhoneCode: '1',
                Country: 'CA',
                Number: '123456789',
                IsPrimary: true,
                Extension: '',
              },
            ],
            Emails: [
              {
                Id: 508593750,
                Address: 'example@email.com',
                IsPrimary: true,
                Type: 'Work',
              },
            ],
            IconMediaLink: {
              Id: 0,
              MediaId: 5707865,
              FileUrl:
                'https://commonmedia.uat-asicentral.com/orders/Artwork/8ede0e38272a45b09e0dc85941bec2a9.png',
              DownloadFileUrl:
                'https://commonmedia.uat-asicentral.com/orders/Artwork/8ede0e38272a45b09e0dc85941bec2a9.png',
              IsVisible: false,
              FileSize: 0,
            },
            OwnerId: 553138,
            AccessLevel: 'Everyone',
            IsVisible: true,
            IsEditable: true,
          },
        },
        IsInHandsDateFlexible: false,
        CarrierName: '',
        ShippingAccountVisible: false,
        IsBlindShip: false,
        Sequence: 1,
      },
    ],
    Supplier: {
      Id: 501254839,
      ExternalId: 8019415,
      Name: 'BNS Promo Inc',
      AsiNumber: '40708',
      IsSupplier: true,
      IsDecorator: false,
      IsAsiMember: true,
      PrimaryEmail: {
        Id: 501519929,
        Address: 'support@bnspromo.com',
        IsPrimary: true,
        Type: 'Work',
      },
      Emails: [
        {
          Id: 501519929,
          Address: 'support@bnspromo.com',
          IsPrimary: true,
          Type: 'Work',
        },
        {
          Id: 501519930,
          Address: 'artben@bnspromo.com',
          IsPrimary: false,
          Type: 'Artwork',
        },
        {
          Id: 501519931,
          Address: 'support@bnspromo.com',
          IsPrimary: false,
          Type: 'Order',
        },
      ],
      PrimaryPhone: '(713) 261-8719',
    },
    Variants: [
      {
        VariantId: 830837349,
        ProductAttributes: [
          {
            Id: 515851371,
            Type: 'MTRL',
            TypeName: 'Material',
            Value: 'Polyester',
            Description: '',
            VendorCode: '',
            IsVisible: true,
          },
          {
            Id: 515851372,
            Type: 'SIZE',
            TypeName: 'Size',
            Value: 'Adjustable',
            Description: '',
            VendorCode: '',
            IsVisible: true,
          },
          {
            Id: 515851373,
            Type: 'PRCL',
            TypeName: 'Product Color',
            Value: 'White',
            Description: '',
            VendorCode: '',
            IsVisible: true,
          },
        ],
        VariantCustomFields: {
          Values: {},
        },
        Id: 506855058,
        CorrelationId: '90d1a995-456e-4810-994d-8b673d51a13f',
        Description: 'White - Adjustable/Polyester',
        IsVisible: true,
        Sequence: 0,
        Quantity: 44,
        QuantityOrdered: 0,
        QuantityInvoiced: 0,
        Price: 0,
        Cost: 22,
        IsTaxable: true,
        CurrencyCode: 'USD',
        CurrencySymbol: '$',
        ConversionRate: 1,
        Totals: {
          Units: 44,
          Amount: 0,
          Cost: 968,
          Margin: -968,
          TaxableAmount: 0,
          SalesTax: 0,
          TaxRate: 0,
        },
        ConversionTotals: {
          Amount: 0,
          Cost: 968,
          Margin: -968,
          TaxableAmount: 0,
        },
        ShippingGroup: 0,
        Status: 'Open',
        IncludeOnPackingList: false,
        VendorNotesVisible: false,
        ConvertedPrice: 0,
        ConvertedCost: 22,
        TotalUnits: 44,
        TotalPrice: 0,
        TotalCost: 968,
        ConvertedTotalPrice: 0,
        ConvertedTotalCost: 968,
        CreateDate: '2022-05-12T14:56:58.023Z',
        CreatedBy: 'Franklin Arsenault',
        MarginPercent: -2200,
      },
      {
        VariantId: 830837349,
        ProductAttributes: [
          {
            Id: 515851368,
            Type: 'MTRL',
            TypeName: 'Material',
            Value: 'Polyester',
            Description: '',
            VendorCode: '',
            IsVisible: true,
          },
          {
            Id: 515851369,
            Type: 'SIZE',
            TypeName: 'Size',
            Value: 'Adjustable',
            Description: '',
            VendorCode: '',
            IsVisible: true,
          },
          {
            Id: 515851370,
            Type: 'PRCL',
            TypeName: 'Product Color',
            Value: 'Gold',
            Description: '',
            VendorCode: '',
            IsVisible: true,
          },
        ],
        VariantCustomFields: {
          Values: {},
        },
        Id: 506855057,
        CorrelationId: '391d4c0f-74a2-4c3e-a4dc-936a45735480',
        Description: 'Gold - Adjustable/Polyester',
        IsVisible: true,
        Sequence: 0,
        Quantity: 44,
        QuantityOrdered: 0,
        QuantityInvoiced: 0,
        Price: 0,
        Cost: 44,
        IsTaxable: true,
        CurrencyCode: 'USD',
        CurrencySymbol: '$',
        ConversionRate: 1,
        Totals: {
          Units: 44,
          Amount: 0,
          Cost: 1936,
          Margin: -1936,
          TaxableAmount: 0,
          SalesTax: 0,
          TaxRate: 0,
        },
        ConversionTotals: {
          Amount: 0,
          Cost: 1936,
          Margin: -1936,
          TaxableAmount: 0,
        },
        ShippingGroup: 0,
        Status: 'Open',
        IncludeOnPackingList: false,
        VendorNotesVisible: false,
        ConvertedPrice: 0,
        ConvertedCost: 44,
        TotalUnits: 44,
        TotalPrice: 0,
        TotalCost: 1936,
        ConvertedTotalPrice: 0,
        ConvertedTotalCost: 1936,
        CreateDate: '2022-05-12T14:56:58.017Z',
        CreatedBy: 'Franklin Arsenault',
        MarginPercent: -4400,
      },
    ],
    ServiceCharges: [
      {
        Id: 506854697,
        CorrelationId: '779315f6-21e0-446a-b0b4-926d4faa6a3f',
        Description: 'Screen Charge',
        IsVisible: true,
        Sequence: 0,
        Quantity: 1,
        QuantityOrdered: 0,
        QuantityInvoiced: 0,
        Price: 44,
        Cost: 44,
        IsTaxable: true,
        CurrencyCode: 'USD',
        CurrencySymbol: '$',
        ConversionRate: 1,
        Totals: {
          Units: 1,
          Amount: 44,
          Cost: 44,
          Margin: 0,
          TaxableAmount: 44,
          SalesTax: 0,
          TaxRate: 0,
        },
        ConversionTotals: {
          Amount: 44,
          Cost: 44,
          Margin: 0,
          TaxableAmount: 44,
          SalesTax: 0,
          TaxRate: 0,
        },
        ShippingGroup: 0,
        Status: 'Open',
        ServiceType: 'SRCH',
        IsRunCharge: false,
        IncludeOnPackingList: false,
        VendorNotesVisible: false,
        ConvertedPrice: 44,
        ConvertedCost: 44,
        TotalUnits: 1,
        TotalPrice: 44,
        TotalCost: 44,
        ConvertedTotalPrice: 44,
        ConvertedTotalCost: 44,
        CreateDate: '2022-05-04T12:28:40.75Z',
        CreatedBy: 'Franklin Arsenault',
        UpdateDate: '2022-05-12T14:55:39.337Z',
        UpdatedBy: 'Franklin Arsenault',
        MarginPercent: 0,
      },
    ],
    Decorations: [
      {
        Id: 503079702,
        LogoColors: [],
        RepeatLogo: false,
        ProofType: 'Blank',
        CommentsVisible: false,
        InstructionsVisible: false,
        Instructions: '',
        ServiceCharges: [
          {
            Id: 502040399,
            CorrelationId: '90f8d0f2-2f56-4463-bab4-33c18a686b76',
            Description: 'Set-up Charge - Silkscreen',
            IsVisible: true,
            Sequence: 0,
            Quantity: 1,
            QuantityOrdered: 0,
            QuantityInvoiced: 0,
            Price: 80,
            Cost: 80,
            IsTaxable: true,
            CurrencyCode: 'USD',
            CurrencySymbol: '$',
            ConversionRate: 1,
            Totals: {
              Units: 1,
              Amount: 80,
              Cost: 80,
              Margin: 0,
              TaxableAmount: 80,
              SalesTax: 0,
              TaxRate: 0,
            },
            ConversionTotals: {
              Amount: 80,
              Cost: 80,
              Margin: 0,
              TaxableAmount: 80,
              SalesTax: 0,
              TaxRate: 0,
            },
            ShippingGroup: 0,
            ServiceType: 'STCH',
            IsRunCharge: false,
            IncludeOnPackingList: false,
            VendorNotesVisible: false,
            ConvertedPrice: 80,
            ConvertedCost: 80,
            TotalUnits: 1,
            TotalPrice: 80,
            TotalCost: 80,
            ConvertedTotalPrice: 80,
            ConvertedTotalCost: 80,
            CreateDate: '2022-05-12T14:56:58.01Z',
            CreatedBy: 'Franklin Arsenault',
            MarginPercent: 0,
          },
          {
            Id: 502040400,
            CorrelationId: '831ef874-bb4e-4d4c-a906-6970cd66c233',
            Description: 'Add. Color Set-up Charge',
            IsVisible: true,
            Sequence: 0,
            Quantity: 676,
            QuantityOrdered: 0,
            QuantityInvoiced: 0,
            Price: 666,
            Cost: 666,
            IsTaxable: true,
            CurrencyCode: 'USD',
            CurrencySymbol: '$',
            ConversionRate: 1,
            Totals: {
              Units: 676,
              Amount: 450216,
              Cost: 450216,
              Margin: 0,
              TaxableAmount: 450216,
              SalesTax: 0,
              TaxRate: 0,
            },
            ConversionTotals: {
              Amount: 450216,
              Cost: 450216,
              Margin: 0,
              TaxableAmount: 450216,
              SalesTax: 0,
              TaxRate: 0,
            },
            ShippingGroup: 0,
            ServiceType: 'CSCH',
            IsRunCharge: false,
            IncludeOnPackingList: false,
            VendorNotesVisible: false,
            ConvertedPrice: 666,
            ConvertedCost: 666,
            TotalUnits: 676,
            TotalPrice: 450216,
            TotalCost: 450216,
            ConvertedTotalPrice: 450216,
            ConvertedTotalCost: 450216,
            CreateDate: '2022-05-12T14:56:58.01Z',
            CreatedBy: 'Franklin Arsenault',
            MarginPercent: 0,
          },
          {
            Id: 502040401,
            CorrelationId: '29d2e5db-7193-4f97-9d3c-81130be2f8c0',
            Description: 'Run Charge',
            IsVisible: true,
            Sequence: 0,
            Quantity: 88,
            QuantityOrdered: 0,
            QuantityInvoiced: 0,
            Price: 7878,
            Cost: 667,
            IsTaxable: true,
            CurrencyCode: 'USD',
            CurrencySymbol: '$',
            ConversionRate: 1,
            Totals: {
              Units: 88,
              Amount: 693264,
              Cost: 58696,
              Margin: 634568,
              TaxableAmount: 693264,
              SalesTax: 0,
              TaxRate: 0,
            },
            ConversionTotals: {
              Amount: 693264,
              Cost: 58696,
              Margin: 634568,
              TaxableAmount: 693264,
              SalesTax: 0,
              TaxRate: 0,
            },
            ShippingGroup: 0,
            ServiceType: 'RNCH',
            IsRunCharge: true,
            IncludeOnPackingList: false,
            VendorNotesVisible: false,
            ConvertedPrice: 7878,
            ConvertedCost: 667,
            TotalUnits: 88,
            TotalPrice: 693264,
            TotalCost: 58696,
            ConvertedTotalPrice: 693264,
            ConvertedTotalCost: 58696,
            CreateDate: '2022-05-12T14:56:58.01Z',
            CreatedBy: 'Franklin Arsenault',
            MarginPercent: 91.5334,
          },
        ],
        Status: 'Open',
        Details: [
          {
            Id: 505310453,
            VariantLinkType: 'All',
            InstructionsVisible: false,
          },
        ],
        Totals: {
          Amount: 1143560,
          Cost: 508992,
          Margin: 634568,
        },
      },
    ],
    Categories: [
      {
        Code: 'C01430003',
        Name: 'CAP & HAT ACCESSORIES',
      },
      {
        Code: 'B02160003',
        Name: 'BASEBALL CAPS',
      },
    ],
    CPN: 'CPN-551238092',
    ShippingGroup: 0,
    Status: 'Open',
    VendorNotesVisible: false,
    TotalUnits: 88,
    TotalPrice: 1143604,
    TotalCost: 511940,
    ConvertedTotalPrice: 1143604,
    ConvertedTotalCost: 511940,
    CreateDate: '2022-05-03T17:51:16.503Z',
    CreatedBy: 'Franklin Arsenault',
    UpdateDate: '2022-05-04T12:28:40.623Z',
    UpdatedBy: 'Franklin Arsenault',
    CustomFields: {
      Values: {},
    },
    QuantityOrdered: 0,
  },
  {
    Id: 504065189,
    CorrelationId: 'b0736228-67e3-49f9-80a3-1ae6f1c12275',
    Type: 'product',
    Name: '8 Inch Beanie',
    Description: '9" Acrylic beanie available in different colors.',
    Relationships: [
      {
        Relationship: 'To Original',
        OrderId: 502188811,
        OrderNumber: '2023-12301063-Enc',
        LineItemId: 504065183,
      },
    ],
    Sequence: 0,
    CurrencyCode: 'USD',
    CurrencySymbol: '$',
    ConversionRate: 1,
    Totals: {
      Units: 0,
      Amount: 77,
      Cost: 88,
      Margin: -11,
      TaxableAmount: 77,
      SalesTax: 0,
      TaxRate: 0,
    },
    ConversionTotals: {
      Amount: 77,
      Cost: 88,
      Margin: -11,
      TaxableAmount: 77,
      SalesTax: 0,
      TaxRate: 0,
    },
    ProductId: 552521839,
    ImageUrl: 'https://media.asicdn.com/images/jpgt/44820000/44824762.jpg',
    Number: '2552',
    Supplier: {
      Id: 512068964,
      ExternalId: 10726,
      Name: 'Direct Caps USA',
      AsiNumber: '48015',
      IsSupplier: true,
      IsDecorator: false,
      IsAsiMember: true,
      Emails: [],
      PrimaryPhone: '(310) 518-2161',
    },
    Decorations: [
      {
        Id: 503079714,
        LogoColors: [],
        RepeatLogo: false,
        ProofType: 'Blank',
        CommentsVisible: false,
        InstructionsVisible: false,
        Instructions: '',
        ServiceCharges: [
          {
            Id: 502040415,
            CorrelationId: '32ef05c6-91ea-4876-8705-a61568fe5e2f',
            Description: 'Set-up Charge',
            IsVisible: true,
            Sequence: 0,
            Quantity: 1,
            QuantityOrdered: 0,
            QuantityInvoiced: 0,
            Price: 77,
            Cost: 88,
            IsTaxable: true,
            CurrencyCode: 'USD',
            CurrencySymbol: '$',
            ConversionRate: 1,
            Totals: {
              Units: 1,
              Amount: 77,
              Cost: 88,
              Margin: -11,
              TaxableAmount: 77,
              SalesTax: 0,
              TaxRate: 0,
            },
            ConversionTotals: {
              Amount: 77,
              Cost: 88,
              Margin: -11,
              TaxableAmount: 77,
              SalesTax: 0,
              TaxRate: 0,
            },
            ShippingGroup: 0,
            ServiceType: 'STCH',
            IsRunCharge: false,
            IncludeOnPackingList: false,
            VendorNotesVisible: false,
            ConvertedPrice: 77,
            ConvertedCost: 88,
            TotalUnits: 1,
            TotalPrice: 77,
            TotalCost: 88,
            ConvertedTotalPrice: 77,
            ConvertedTotalCost: 88,
            CreateDate: '2022-05-12T16:15:26.92Z',
            CreatedBy: 'Franklin Arsenault',
            MarginPercent: -14.2857,
          },
        ],
        Status: 'Open',
        Details: [
          {
            Id: 505310467,
            VariantLinkType: 'All',
            InstructionsVisible: false,
          },
        ],
        Totals: {
          Amount: 77,
          Cost: 88,
          Margin: -11,
        },
      },
    ],
    Categories: [
      {
        Code: 'C01560003',
        Name: 'CAPS & HATS',
      },
    ],
    CPN: 'CPN-553123336',
    ShippingGroup: 0,
    Status: 'Open',
    VendorNotesVisible: false,
    TotalUnits: 0,
    TotalPrice: 77,
    TotalCost: 88,
    ConvertedTotalPrice: 77,
    ConvertedTotalCost: 88,
    CreateDate: '2022-05-03T17:51:16.507Z',
    CreatedBy: 'Franklin Arsenault',
    UpdateDate: '2022-05-04T15:43:54.87Z',
    UpdatedBy: 'Franklin Arsenault',
    CustomFields: {
      Values: {},
    },
    Variants: [],
    ServiceCharges: [],
    QuantityOrdered: 0,
  },
  {
    Id: 504065190,
    CorrelationId: '9129a7fa-081d-4088-a76c-dcbf63940ff0',
    Type: 'product',
    Name: 'Acrylic Beanie Lined knit w/ Custom Embroidery Two Tone Cap',
    Description:
      'Wow your customers this winter with our trendy Lined knit beanies! This fashionable winter beanie is made of 100% acrylic and comes in Black and White with white lining at bottom. Conveniently made in flexible one size to fit adult sizes, this also features a large imprint area of 4" W x 2" H, perfect for brand exposure. This fashionable beanie is ideal for winter outings, camping and hiking activities. Give these away in your next trade show and see what great difference it makes!',
    Relationships: [
      {
        Relationship: 'To Original',
        OrderId: 502188811,
        OrderNumber: '2023-12301063-Enc',
        LineItemId: 504065184,
      },
    ],
    Sequence: 0,
    CurrencyCode: 'USD',
    CurrencySymbol: '$',
    ConversionRate: 1,
    Totals: {
      Units: 0,
      Amount: 0,
      Cost: 0,
      Margin: 0,
      TaxableAmount: 0,
      SalesTax: 0,
      TaxRate: 0,
    },
    ConversionTotals: {
      Amount: 0,
      Cost: 0,
      Margin: 0,
      TaxableAmount: 0,
      SalesTax: 0,
      TaxRate: 0,
    },
    ProductId: 552499009,
    ImageUrl: 'https://media.asicdn.com/images/jpgt/38090000/38092852.jpg',
    Number: 'BNFL59',
    Supplier: {
      Id: 500098540,
      ExternalId: 5732278,
      Name: 'imprintID',
      AsiNumber: '73651',
      IsSupplier: true,
      IsDecorator: false,
      IsAsiMember: true,
      PrimaryEmail: {
        Id: 500065567,
        Address: 'sales@imprintid.com',
        IsPrimary: true,
        Type: 'Work',
      },
      Emails: [
        {
          Id: 500065567,
          Address: 'sales@imprintid.com',
          IsPrimary: true,
          Type: 'Work',
        },
        {
          Id: 500065568,
          Address: 'orders@imprintid.com',
          IsPrimary: false,
          Type: 'Order',
        },
        {
          Id: 500065569,
          Address: 'orders@imprintid.com',
          IsPrimary: false,
          Type: 'Artwork',
        },
      ],
      PrimaryPhone: '(703) 991-8087',
    },
    Categories: [
      {
        Code: 'C01560003',
        Name: 'CAPS & HATS',
      },
    ],
    CPN: 'CPN-553100506',
    ShippingGroup: 0,
    Status: 'Open',
    VendorNotesVisible: false,
    TotalUnits: 0,
    TotalPrice: 0,
    TotalCost: 0,
    ConvertedTotalPrice: 0,
    ConvertedTotalCost: 0,
    CreateDate: '2022-05-03T17:51:16.507Z',
    CreatedBy: 'Franklin Arsenault',
    UpdateDate: '2022-05-04T15:43:54.87Z',
    UpdatedBy: 'Franklin Arsenault',
    CustomFields: {
      Values: {},
    },
    Variants: [],
    ServiceCharges: [],
    Decorations: [],
    QuantityOrdered: 0,
  },
  {
    Id: 504065242,
    CorrelationId: 'afa6d518-33a5-4692-a884-47d5e330f337',
    Type: 'product',
    Name: '3-Piece Low Min Bella Canvas Full Color 4.4oz Cotton T Shirt',
    Description:
      'Get customers excited this summer with our 3-Piece Low Min Bella Canvas Full Color Men\'s Cotton T Shirt with Full color DTG imprinting. This round neck T-shirt is ideal for sports & outdoor activities and features a large imprint area of 12.00"W x 12.00"H as well as on left/ right chest, ideal for Maximum Brand exposure. It is made of 4.4 oz 100% Airlume Combed and Ringspun Cotton. With 32 singles for extreme comfort, this trendy t shirt also feature Shoulder taping & Sideseamed. Order these Tshirts today a',
    Relationships: [],
    Sequence: 0,
    CurrencyCode: 'USD',
    CurrencySymbol: '$',
    ConversionRate: 1,
    Totals: {
      Units: 0,
      Amount: 445,
      Cost: 52,
      Margin: 393,
      TaxableAmount: 0,
      SalesTax: 0,
      TaxRate: 0,
    },
    ConversionTotals: {
      Amount: 445,
      Cost: 52,
      Margin: 393,
      TaxableAmount: 0,
      SalesTax: 0,
      TaxRate: 0,
    },
    ProductId: 553302654,
    ImageUrl: 'https://media.asicdn.com/images/jpgt/45360000/45369593.jpg',
    Number: 'TS3005C',
    ShippingDetail: {
      Id: 505369225,
      From: {
        Id: 514516958,
        Address: {
          Id: 0,
          Phone: {
            Id: 0,
            Type: 'Other',
            PhoneCode: '1',
            Country: 'US',
          },
          IsPrimary: false,
        },
        Company: {
          IsCompany: true,
          IsPerson: false,
          Id: 500098540,
          Name: 'imprintID',
          Addresses: [],
          Phones: [
            {
              Id: 500125324,
              Type: 'Other',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(877) 385-7785',
              IsPrimary: false,
            },
            {
              Id: 500125325,
              Type: 'OfficeFax',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(703) 991-8087',
              IsPrimary: true,
            },
            {
              Id: 500125326,
              Type: 'OrdersFax',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(703) 991-8087',
              IsPrimary: false,
            },
          ],
          Emails: [
            {
              Id: 500065567,
              Address: 'sales@imprintid.com',
              IsPrimary: true,
              Type: 'Work',
            },
            {
              Id: 500065568,
              Address: 'orders@imprintid.com',
              IsPrimary: false,
              Type: 'Order',
            },
            {
              Id: 500065569,
              Address: 'orders@imprintid.com',
              IsPrimary: false,
              Type: 'Artwork',
            },
          ],
          OwnerId: 45821,
          AccessLevel: 'Everyone',
          IsVisible: false,
          IsEditable: false,
        },
        Party: {
          IsCompany: true,
          IsPerson: false,
          Id: 500098540,
          Name: 'imprintID',
          Addresses: [],
          Phones: [
            {
              Id: 500125324,
              Type: 'Other',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(877) 385-7785',
              IsPrimary: false,
            },
            {
              Id: 500125325,
              Type: 'OfficeFax',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(703) 991-8087',
              IsPrimary: true,
            },
            {
              Id: 500125326,
              Type: 'OrdersFax',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(703) 991-8087',
              IsPrimary: false,
            },
          ],
          Emails: [
            {
              Id: 500065567,
              Address: 'sales@imprintid.com',
              IsPrimary: true,
              Type: 'Work',
            },
            {
              Id: 500065568,
              Address: 'orders@imprintid.com',
              IsPrimary: false,
              Type: 'Order',
            },
            {
              Id: 500065569,
              Address: 'orders@imprintid.com',
              IsPrimary: false,
              Type: 'Artwork',
            },
          ],
          OwnerId: 45821,
          AccessLevel: 'Everyone',
          IsVisible: false,
          IsEditable: false,
        },
      },
      To: {
        Id: 514516959,
        Name: '1234Y Aturi',
        EmailAddress: '123testers@testester.com',
        Address: {
          Id: 0,
          Line1: '4800 Street Rd',
          City: 'Feasterville-Trevose',
          State: 'PA',
          PostalCode: '236236',
          Country: 'United States',
          CountryType: 'US',
          Phone: {
            Id: 0,
            Type: 'Office',
            PhoneCode: '1',
            Country: 'US',
            Number: '123456789',
            Extension: '',
          },
          IsPrimary: true,
        },
        Company: {
          IsCompany: true,
          IsPerson: false,
          Id: 513543216,
          Name: 'ASI Garments :P ;)',
          Addresses: [
            {
              Id: 506710964,
              Name: 'ASI Garments :P ;)',
              Line1: '1003 Hamilton Blvd NE',
              City: 'Airdrie',
              County: '',
              State: 'AB',
              PostalCode: 'T4A 0R1',
              Country: 'Canada',
              CountryType: 'CA',
              IsPrimary: true,
              Type: 'GNRL',
            },
          ],
          Phones: [
            {
              Id: 510416200,
              Type: 'Office',
              PhoneCode: '1',
              Country: 'CA',
              Number: '123456789',
              IsPrimary: true,
              Extension: '',
            },
          ],
          Emails: [
            {
              Id: 508593750,
              Address: 'example@email.com',
              IsPrimary: true,
              Type: 'Work',
            },
          ],
          IconMediaLink: {
            Id: 0,
            MediaId: 5707865,
            FileUrl:
              'https://commonmedia.uat-asicentral.com/orders/Artwork/8ede0e38272a45b09e0dc85941bec2a9.png',
            DownloadFileUrl:
              'https://commonmedia.uat-asicentral.com/orders/Artwork/8ede0e38272a45b09e0dc85941bec2a9.png',
            IsVisible: false,
            FileSize: 0,
          },
          OwnerId: 553138,
          AccessLevel: 'Everyone',
          IsVisible: true,
          IsEditable: true,
        },
      },
      CarrierName: '',
      ShippingAccountVisible: false,
      Sequence: 1,
    },
    ShippingDetails: [
      {
        Id: 505369225,
        From: {
          Id: 514516958,
          Address: {
            Id: 0,
            Phone: {
              Id: 0,
              Type: 'Other',
              PhoneCode: '1',
              Country: 'US',
            },
            IsPrimary: false,
          },
          Company: {
            IsCompany: true,
            IsPerson: false,
            Id: 500098540,
            Name: 'imprintID',
            Addresses: [],
            Phones: [
              {
                Id: 500125324,
                Type: 'Other',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(877) 385-7785',
                IsPrimary: false,
              },
              {
                Id: 500125325,
                Type: 'OfficeFax',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(703) 991-8087',
                IsPrimary: true,
              },
              {
                Id: 500125326,
                Type: 'OrdersFax',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(703) 991-8087',
                IsPrimary: false,
              },
            ],
            Emails: [
              {
                Id: 500065567,
                Address: 'sales@imprintid.com',
                IsPrimary: true,
                Type: 'Work',
              },
              {
                Id: 500065568,
                Address: 'orders@imprintid.com',
                IsPrimary: false,
                Type: 'Order',
              },
              {
                Id: 500065569,
                Address: 'orders@imprintid.com',
                IsPrimary: false,
                Type: 'Artwork',
              },
            ],
            OwnerId: 45821,
            AccessLevel: 'Everyone',
            IsVisible: false,
            IsEditable: false,
          },
          Party: {
            IsCompany: true,
            IsPerson: false,
            Id: 500098540,
            Name: 'imprintID',
            Addresses: [],
            Phones: [
              {
                Id: 500125324,
                Type: 'Other',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(877) 385-7785',
                IsPrimary: false,
              },
              {
                Id: 500125325,
                Type: 'OfficeFax',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(703) 991-8087',
                IsPrimary: true,
              },
              {
                Id: 500125326,
                Type: 'OrdersFax',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(703) 991-8087',
                IsPrimary: false,
              },
            ],
            Emails: [
              {
                Id: 500065567,
                Address: 'sales@imprintid.com',
                IsPrimary: true,
                Type: 'Work',
              },
              {
                Id: 500065568,
                Address: 'orders@imprintid.com',
                IsPrimary: false,
                Type: 'Order',
              },
              {
                Id: 500065569,
                Address: 'orders@imprintid.com',
                IsPrimary: false,
                Type: 'Artwork',
              },
            ],
            OwnerId: 45821,
            AccessLevel: 'Everyone',
            IsVisible: false,
            IsEditable: false,
          },
        },
        To: {
          Id: 514516959,
          Name: '1234Y Aturi',
          EmailAddress: '123testers@testester.com',
          Address: {
            Id: 0,
            Line1: '4800 Street Rd',
            City: 'Feasterville-Trevose',
            State: 'PA',
            PostalCode: '236236',
            Country: 'United States',
            CountryType: 'US',
            Phone: {
              Id: 0,
              Type: 'Office',
              PhoneCode: '1',
              Country: 'US',
              Number: '123456789',
              Extension: '',
            },
            IsPrimary: true,
          },
          Company: {
            IsCompany: true,
            IsPerson: false,
            Id: 513543216,
            Name: 'ASI Garments :P ;)',
            Addresses: [
              {
                Id: 506710964,
                Name: 'ASI Garments :P ;)',
                Line1: '1003 Hamilton Blvd NE',
                City: 'Airdrie',
                County: '',
                State: 'AB',
                PostalCode: 'T4A 0R1',
                Country: 'Canada',
                CountryType: 'CA',
                IsPrimary: true,
                Type: 'GNRL',
              },
            ],
            Phones: [
              {
                Id: 510416200,
                Type: 'Office',
                PhoneCode: '1',
                Country: 'CA',
                Number: '123456789',
                IsPrimary: true,
                Extension: '',
              },
            ],
            Emails: [
              {
                Id: 508593750,
                Address: 'example@email.com',
                IsPrimary: true,
                Type: 'Work',
              },
            ],
            IconMediaLink: {
              Id: 0,
              MediaId: 5707865,
              FileUrl:
                'https://commonmedia.uat-asicentral.com/orders/Artwork/8ede0e38272a45b09e0dc85941bec2a9.png',
              DownloadFileUrl:
                'https://commonmedia.uat-asicentral.com/orders/Artwork/8ede0e38272a45b09e0dc85941bec2a9.png',
              IsVisible: false,
              FileSize: 0,
            },
            OwnerId: 553138,
            AccessLevel: 'Everyone',
            IsVisible: true,
            IsEditable: true,
          },
        },
        CarrierName: '',
        ShippingAccountVisible: false,
        Sequence: 1,
      },
    ],
    Supplier: {
      Id: 500098540,
      ExternalId: 5732278,
      Name: 'imprintID',
      AsiNumber: '73651',
      IsSupplier: true,
      IsDecorator: false,
      IsAsiMember: true,
      PrimaryEmail: {
        Id: 500065567,
        Address: 'sales@imprintid.com',
        IsPrimary: true,
        Type: 'Work',
      },
      Emails: [
        {
          Id: 500065567,
          Address: 'sales@imprintid.com',
          IsPrimary: true,
          Type: 'Work',
        },
        {
          Id: 500065568,
          Address: 'orders@imprintid.com',
          IsPrimary: false,
          Type: 'Order',
        },
        {
          Id: 500065569,
          Address: 'orders@imprintid.com',
          IsPrimary: false,
          Type: 'Artwork',
        },
      ],
      PrimaryPhone: '(703) 991-8087',
    },
    Variants: [],
    ServiceCharges: [
      {
        Id: 506854710,
        CorrelationId: 'c261457b-2ccb-42cb-9d68-346777f00f9b',
        Description: 'Mold Charge',
        IsVisible: true,
        Sequence: 0,
        Quantity: 1,
        QuantityOrdered: 0,
        QuantityInvoiced: 0,
        Price: 445,
        Cost: 52,
        IsTaxable: false,
        CurrencyCode: 'USD',
        CurrencySymbol: '$',
        ConversionRate: 1,
        Totals: {
          Units: 1,
          Amount: 445,
          Cost: 52,
          Margin: 393,
          TaxableAmount: 0,
          SalesTax: 0,
          TaxRate: 0,
        },
        ConversionTotals: {
          Amount: 445,
          Cost: 52,
          Margin: 393,
          TaxableAmount: 0,
          SalesTax: 0,
          TaxRate: 0,
        },
        ShippingGroup: 0,
        Status: 'Open',
        ServiceType: 'MLCH',
        IsRunCharge: false,
        IncludeOnPackingList: false,
        VendorNotesVisible: false,
        ConvertedPrice: 445,
        ConvertedCost: 52,
        TotalUnits: 1,
        TotalPrice: 445,
        TotalCost: 52,
        ConvertedTotalPrice: 445,
        ConvertedTotalCost: 52,
        CreateDate: '2022-05-04T15:44:31.123Z',
        CreatedBy: 'Franklin Arsenault',
        MarginPercent: 88.3146,
      },
    ],
    Decorations: [
      {
        Id: 503079424,
        LogoColors: [],
        RepeatLogo: false,
        ProofType: 'Blank',
        CommentsVisible: false,
        InstructionsVisible: false,
        Instructions: '',
        Status: 'Open',
        Details: [
          {
            Id: 505310066,
            VariantLinkType: 'All',
            InstructionsVisible: false,
          },
        ],
        ServiceCharges: [],
        Totals: {
          Amount: 0,
          Cost: 0,
          Margin: 0,
        },
      },
    ],
    Categories: [
      {
        Code: 'T00250003',
        Name: 'T-SHIRTS',
      },
    ],
    CPN: 'CPN-553302654',
    ShippingGroup: 0,
    Status: 'Open',
    VendorNotesVisible: false,
    TotalUnits: 0,
    TotalPrice: 445,
    TotalCost: 52,
    ConvertedTotalPrice: 445,
    ConvertedTotalCost: 52,
    CreateDate: '2022-05-04T15:43:55.197Z',
    CreatedBy: 'Franklin Arsenault',
    UpdateDate: '2022-05-04T15:44:30.913Z',
    UpdatedBy: 'Franklin Arsenault',
    CustomFields: {
      Values: {},
    },
    QuantityOrdered: 0,
  },
  {
    Id: 504065243,
    CorrelationId: 'fb61161c-211e-46d6-bf57-7e8b356f5f55',
    Type: 'product',
    Name: 'Augusta Sportswear V-Neck Jersey with Striped Sleeves',
    Description:
      'They\'re bound to hit a grand slam in this retro-looking V-neck jersey from Augusta Sportswear®!  Featuring striped sleeves and constructed of 50/50 cotton/polyester knit, this jersey is tailored to last season after season.  Has a contrast color 1" x 1" rib-knit V-neck collar, two white stripes on set-in double needle stitched sleeves and double-needle stitched bottom hem.  Available in a variety of colors and sizes. Sold as a blank product only.',
    Relationships: [],
    Sequence: 0,
    CurrencyCode: 'USD',
    CurrencySymbol: '$',
    ConversionRate: 1,
    Totals: {
      Units: 15,
      Amount: 78.96,
      Cost: 75,
      Margin: 3.96,
      TaxableAmount: 78.96,
      SalesTax: 0,
      TaxRate: 0,
    },
    ConversionTotals: {
      Amount: 78.96,
      Cost: 75,
      Margin: 3.96,
      TaxableAmount: 78.96,
      SalesTax: 0,
      TaxRate: 0,
    },
    ProductId: 6107350,
    ImageUrl: 'https://media.asicdn.com/images/jpgt/32210000/32218507.jpg',
    Number: '360',
    ShippingDetail: {
      Id: 505369226,
      From: {
        Id: 514516960,
        Address: {
          Id: 0,
          Phone: {
            Id: 0,
            Type: 'Other',
            PhoneCode: '1',
            Country: 'US',
          },
          IsPrimary: false,
        },
        Company: {
          IsCompany: true,
          IsPerson: false,
          Id: 500084429,
          Name: 'S & S Activewear',
          Addresses: [],
          Phones: [
            {
              Id: 500110768,
              Type: 'Other',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(800) 523-2155',
              IsPrimary: true,
            },
            {
              Id: 500110769,
              Type: 'Office',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(630) 679-9940',
              IsPrimary: false,
            },
            {
              Id: 500110770,
              Type: 'OfficeFax',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(630) 679-9941',
              IsPrimary: false,
            },
            {
              Id: 500110771,
              Type: 'OrdersFax',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(630) 679-9941',
              IsPrimary: false,
            },
          ],
          Emails: [
            {
              Id: 500059878,
              Address: 'info@ssactivewear.com',
              IsPrimary: true,
              Type: 'Work',
            },
            {
              Id: 500059879,
              Address: 'orders@ssactivewear.com',
              IsPrimary: false,
              Type: 'Order',
            },
          ],
          OwnerId: 100423,
          AccessLevel: 'Everyone',
          IsVisible: false,
          IsEditable: false,
        },
        Party: {
          IsCompany: true,
          IsPerson: false,
          Id: 500084429,
          Name: 'S & S Activewear',
          Addresses: [],
          Phones: [
            {
              Id: 500110768,
              Type: 'Other',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(800) 523-2155',
              IsPrimary: true,
            },
            {
              Id: 500110769,
              Type: 'Office',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(630) 679-9940',
              IsPrimary: false,
            },
            {
              Id: 500110770,
              Type: 'OfficeFax',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(630) 679-9941',
              IsPrimary: false,
            },
            {
              Id: 500110771,
              Type: 'OrdersFax',
              PhoneCode: '1',
              Country: 'USA',
              Number: '(630) 679-9941',
              IsPrimary: false,
            },
          ],
          Emails: [
            {
              Id: 500059878,
              Address: 'info@ssactivewear.com',
              IsPrimary: true,
              Type: 'Work',
            },
            {
              Id: 500059879,
              Address: 'orders@ssactivewear.com',
              IsPrimary: false,
              Type: 'Order',
            },
          ],
          OwnerId: 100423,
          AccessLevel: 'Everyone',
          IsVisible: false,
          IsEditable: false,
        },
      },
      To: {
        Id: 514516961,
        Name: '1234Y Aturi',
        EmailAddress: '123testers@testester.com',
        Address: {
          Id: 0,
          Line1: '4800 Street Rd',
          City: 'Feasterville-Trevose',
          State: 'PA',
          PostalCode: '236236',
          Country: 'United States',
          CountryType: 'US',
          Phone: {
            Id: 0,
            Type: 'Office',
            PhoneCode: '1',
            Country: 'US',
            Number: '123456789',
            Extension: '',
          },
          IsPrimary: true,
        },
        Company: {
          IsCompany: true,
          IsPerson: false,
          Id: 513543216,
          Name: 'ASI Garments :P ;)',
          Addresses: [
            {
              Id: 506710964,
              Name: 'ASI Garments :P ;)',
              Line1: '1003 Hamilton Blvd NE',
              City: 'Airdrie',
              County: '',
              State: 'AB',
              PostalCode: 'T4A 0R1',
              Country: 'Canada',
              CountryType: 'CA',
              IsPrimary: true,
              Type: 'GNRL',
            },
          ],
          Phones: [
            {
              Id: 510416200,
              Type: 'Office',
              PhoneCode: '1',
              Country: 'CA',
              Number: '123456789',
              IsPrimary: true,
              Extension: '',
            },
          ],
          Emails: [
            {
              Id: 508593750,
              Address: 'example@email.com',
              IsPrimary: true,
              Type: 'Work',
            },
          ],
          IconMediaLink: {
            Id: 0,
            MediaId: 5707865,
            FileUrl:
              'https://commonmedia.uat-asicentral.com/orders/Artwork/8ede0e38272a45b09e0dc85941bec2a9.png',
            DownloadFileUrl:
              'https://commonmedia.uat-asicentral.com/orders/Artwork/8ede0e38272a45b09e0dc85941bec2a9.png',
            IsVisible: false,
            FileSize: 0,
          },
          OwnerId: 553138,
          AccessLevel: 'Everyone',
          IsVisible: true,
          IsEditable: true,
        },
      },
      CarrierName: '',
      ShippingAccountVisible: false,
      Sequence: 1,
    },
    ShippingDetails: [
      {
        Id: 505369226,
        From: {
          Id: 514516960,
          Address: {
            Id: 0,
            Phone: {
              Id: 0,
              Type: 'Other',
              PhoneCode: '1',
              Country: 'US',
            },
            IsPrimary: false,
          },
          Company: {
            IsCompany: true,
            IsPerson: false,
            Id: 500084429,
            Name: 'S & S Activewear',
            Addresses: [],
            Phones: [
              {
                Id: 500110768,
                Type: 'Other',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(800) 523-2155',
                IsPrimary: true,
              },
              {
                Id: 500110769,
                Type: 'Office',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(630) 679-9940',
                IsPrimary: false,
              },
              {
                Id: 500110770,
                Type: 'OfficeFax',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(630) 679-9941',
                IsPrimary: false,
              },
              {
                Id: 500110771,
                Type: 'OrdersFax',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(630) 679-9941',
                IsPrimary: false,
              },
            ],
            Emails: [
              {
                Id: 500059878,
                Address: 'info@ssactivewear.com',
                IsPrimary: true,
                Type: 'Work',
              },
              {
                Id: 500059879,
                Address: 'orders@ssactivewear.com',
                IsPrimary: false,
                Type: 'Order',
              },
            ],
            OwnerId: 100423,
            AccessLevel: 'Everyone',
            IsVisible: false,
            IsEditable: false,
          },
          Party: {
            IsCompany: true,
            IsPerson: false,
            Id: 500084429,
            Name: 'S & S Activewear',
            Addresses: [],
            Phones: [
              {
                Id: 500110768,
                Type: 'Other',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(800) 523-2155',
                IsPrimary: true,
              },
              {
                Id: 500110769,
                Type: 'Office',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(630) 679-9940',
                IsPrimary: false,
              },
              {
                Id: 500110770,
                Type: 'OfficeFax',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(630) 679-9941',
                IsPrimary: false,
              },
              {
                Id: 500110771,
                Type: 'OrdersFax',
                PhoneCode: '1',
                Country: 'USA',
                Number: '(630) 679-9941',
                IsPrimary: false,
              },
            ],
            Emails: [
              {
                Id: 500059878,
                Address: 'info@ssactivewear.com',
                IsPrimary: true,
                Type: 'Work',
              },
              {
                Id: 500059879,
                Address: 'orders@ssactivewear.com',
                IsPrimary: false,
                Type: 'Order',
              },
            ],
            OwnerId: 100423,
            AccessLevel: 'Everyone',
            IsVisible: false,
            IsEditable: false,
          },
        },
        To: {
          Id: 514516961,
          Name: '1234Y Aturi',
          EmailAddress: '123testers@testester.com',
          Address: {
            Id: 0,
            Line1: '4800 Street Rd',
            City: 'Feasterville-Trevose',
            State: 'PA',
            PostalCode: '236236',
            Country: 'United States',
            CountryType: 'US',
            Phone: {
              Id: 0,
              Type: 'Office',
              PhoneCode: '1',
              Country: 'US',
              Number: '123456789',
              Extension: '',
            },
            IsPrimary: true,
          },
          Company: {
            IsCompany: true,
            IsPerson: false,
            Id: 513543216,
            Name: 'ASI Garments :P ;)',
            Addresses: [
              {
                Id: 506710964,
                Name: 'ASI Garments :P ;)',
                Line1: '1003 Hamilton Blvd NE',
                City: 'Airdrie',
                County: '',
                State: 'AB',
                PostalCode: 'T4A 0R1',
                Country: 'Canada',
                CountryType: 'CA',
                IsPrimary: true,
                Type: 'GNRL',
              },
            ],
            Phones: [
              {
                Id: 510416200,
                Type: 'Office',
                PhoneCode: '1',
                Country: 'CA',
                Number: '123456789',
                IsPrimary: true,
                Extension: '',
              },
            ],
            Emails: [
              {
                Id: 508593750,
                Address: 'example@email.com',
                IsPrimary: true,
                Type: 'Work',
              },
            ],
            IconMediaLink: {
              Id: 0,
              MediaId: 5707865,
              FileUrl:
                'https://commonmedia.uat-asicentral.com/orders/Artwork/8ede0e38272a45b09e0dc85941bec2a9.png',
              DownloadFileUrl:
                'https://commonmedia.uat-asicentral.com/orders/Artwork/8ede0e38272a45b09e0dc85941bec2a9.png',
              IsVisible: false,
              FileSize: 0,
            },
            OwnerId: 553138,
            AccessLevel: 'Everyone',
            IsVisible: true,
            IsEditable: true,
          },
        },
        CarrierName: '',
        ShippingAccountVisible: false,
        Sequence: 1,
      },
    ],
    Supplier: {
      Id: 500084429,
      ExternalId: 3112,
      Name: 'S & S Activewear',
      AsiNumber: '84358',
      IsSupplier: true,
      IsDecorator: false,
      IsAsiMember: true,
      PrimaryEmail: {
        Id: 500059878,
        Address: 'info@ssactivewear.com',
        IsPrimary: true,
        Type: 'Work',
      },
      Emails: [
        {
          Id: 500059878,
          Address: 'info@ssactivewear.com',
          IsPrimary: true,
          Type: 'Work',
        },
        {
          Id: 500059879,
          Address: 'orders@ssactivewear.com',
          IsPrimary: false,
          Type: 'Order',
        },
      ],
      PrimaryPhone: '(800) 523-2155',
    },
    Variants: [
      {
        VariantId: 848411796,
        ProductAttributes: [
          {
            Id: 515850586,
            Type: 'MTRL',
            TypeName: 'Material',
            Value: 'Blend: Cotton/Polyester Knit (50/50)',
            Description: '',
            VendorCode: '',
            IsVisible: true,
          },
          {
            Id: 515850587,
            Type: 'SIZE',
            TypeName: 'Size',
            Value: '2XL',
            Description: '',
            VendorCode: '7',
            IsVisible: true,
          },
          {
            Id: 515850588,
            Type: 'PRCL',
            TypeName: 'Product Color',
            Value: 'Kelly/ White',
            Description: '',
            VendorCode: '60',
            IsVisible: true,
          },
        ],
        VariantCustomFields: {
          Values: {},
        },
        Id: 506854713,
        CorrelationId: '7f35cf14-84a4-4432-a5bd-ce03c50d292d',
        Description: '2XL - Kelly/ White/Blend: Cotton/Polyester Knit (50/50)',
        IsVisible: true,
        Sequence: 0,
        Quantity: 5,
        QuantityOrdered: 0,
        QuantityInvoiced: 0,
        Price: 5.264,
        Cost: 5,
        IsTaxable: true,
        CurrencyCode: 'USD',
        CurrencySymbol: '$',
        ConversionRate: 1,
        Totals: {
          Units: 5,
          Amount: 26.32,
          Cost: 25,
          Margin: 1.32,
          TaxableAmount: 26.32,
          SalesTax: 0,
          TaxRate: 0,
        },
        ConversionTotals: {
          Amount: 26.32,
          Cost: 25,
          Margin: 1.32,
          TaxableAmount: 26.32,
        },
        SKU: 'B06334607',
        ShippingGroup: 0,
        Status: 'Open',
        IncludeOnPackingList: false,
        VendorNotesVisible: false,
        ConvertedPrice: 5.264,
        ConvertedCost: 5,
        TotalUnits: 5,
        TotalPrice: 26.32,
        TotalCost: 25,
        ConvertedTotalPrice: 26.32,
        ConvertedTotalCost: 25,
        CreateDate: '2022-05-04T15:45:33.93Z',
        CreatedBy: 'Franklin Arsenault',
        MarginPercent: 5.0152,
      },
      {
        VariantId: 848411796,
        ProductAttributes: [
          {
            Id: 515850583,
            Type: 'MTRL',
            TypeName: 'Material',
            Value: 'Blend: Cotton/Polyester Knit (50/50)',
            Description: '',
            VendorCode: '',
            IsVisible: true,
          },
          {
            Id: 515850584,
            Type: 'SIZE',
            TypeName: 'Size',
            Value: '2XL',
            Description: '',
            VendorCode: '7',
            IsVisible: true,
          },
          {
            Id: 515850585,
            Type: 'PRCL',
            TypeName: 'Product Color',
            Value: 'Black/ White',
            Description: '',
            VendorCode: '50',
            IsVisible: true,
          },
        ],
        VariantCustomFields: {
          Values: {},
        },
        Id: 506854712,
        CorrelationId: '6c1c72d1-2544-4071-9695-25609bafe91f',
        Description: '2XL - Black/ White/Blend: Cotton/Polyester Knit (50/50)',
        IsVisible: true,
        Sequence: 0,
        Quantity: 5,
        QuantityOrdered: 0,
        QuantityInvoiced: 0,
        Price: 5.264,
        Cost: 5,
        IsTaxable: true,
        CurrencyCode: 'USD',
        CurrencySymbol: '$',
        ConversionRate: 1,
        Totals: {
          Units: 5,
          Amount: 26.32,
          Cost: 25,
          Margin: 1.32,
          TaxableAmount: 26.32,
          SalesTax: 0,
          TaxRate: 0,
        },
        ConversionTotals: {
          Amount: 26.32,
          Cost: 25,
          Margin: 1.32,
          TaxableAmount: 26.32,
        },
        SKU: 'B06334507',
        ShippingGroup: 0,
        Status: 'Open',
        IncludeOnPackingList: false,
        VendorNotesVisible: false,
        ConvertedPrice: 5.264,
        ConvertedCost: 5,
        TotalUnits: 5,
        TotalPrice: 26.32,
        TotalCost: 25,
        ConvertedTotalPrice: 26.32,
        ConvertedTotalCost: 25,
        CreateDate: '2022-05-04T15:45:33.923Z',
        CreatedBy: 'Franklin Arsenault',
        MarginPercent: 5.0152,
      },
      {
        VariantId: 848411792,
        ProductAttributes: [
          {
            Id: 515850580,
            Type: 'MTRL',
            TypeName: 'Material',
            Value: 'Blend: Cotton/Polyester Knit (50/50)',
            Description: '',
            VendorCode: '',
            IsVisible: true,
          },
          {
            Id: 515850581,
            Type: 'SIZE',
            TypeName: 'Size',
            Value: 'S',
            Description: '',
            VendorCode: '3',
            IsVisible: true,
          },
          {
            Id: 515850582,
            Type: 'PRCL',
            TypeName: 'Product Color',
            Value: 'Black/ White',
            Description: '',
            VendorCode: '50',
            IsVisible: true,
          },
        ],
        VariantCustomFields: {
          Values: {},
        },
        Id: 506854711,
        CorrelationId: '1e475606-f3b3-49d2-8df0-037debf91cf8',
        Description: 'S - Black/ White/Blend: Cotton/Polyester Knit (50/50)',
        IsVisible: true,
        Sequence: 0,
        Quantity: 5,
        QuantityOrdered: 0,
        QuantityInvoiced: 0,
        Price: 5.264,
        Cost: 5,
        IsTaxable: true,
        CurrencyCode: 'USD',
        CurrencySymbol: '$',
        ConversionRate: 1,
        Totals: {
          Units: 5,
          Amount: 26.32,
          Cost: 25,
          Margin: 1.32,
          TaxableAmount: 26.32,
          SalesTax: 0,
          TaxRate: 0,
        },
        ConversionTotals: {
          Amount: 26.32,
          Cost: 25,
          Margin: 1.32,
          TaxableAmount: 26.32,
        },
        SKU: 'B06334503',
        ShippingGroup: 0,
        Status: 'Open',
        IncludeOnPackingList: false,
        VendorNotesVisible: false,
        ConvertedPrice: 5.264,
        ConvertedCost: 5,
        TotalUnits: 5,
        TotalPrice: 26.32,
        TotalCost: 25,
        ConvertedTotalPrice: 26.32,
        ConvertedTotalCost: 25,
        CreateDate: '2022-05-04T15:45:33.917Z',
        CreatedBy: 'Franklin Arsenault',
        MarginPercent: 5.0152,
      },
    ],
    ServiceCharges: [],
    Decorations: [
      {
        Id: 503079425,
        LogoColors: [],
        RepeatLogo: false,
        ProofType: 'Blank',
        CommentsVisible: false,
        InstructionsVisible: false,
        Instructions: '',
        Status: 'Open',
        Details: [
          {
            Id: 505310067,
            VariantLinkType: 'All',
            InstructionsVisible: false,
          },
        ],
        ServiceCharges: [],
        Totals: {
          Amount: 0,
          Cost: 0,
          Margin: 0,
        },
      },
    ],
    Categories: [
      {
        Code: 'T00250003',
        Name: 'T-SHIRTS',
      },
      {
        Code: 'U01700003',
        Name: 'UNIFORMS',
      },
    ],
    CPN: 'CPN-6107350',
    ShippingGroup: 0,
    Status: 'Open',
    VendorNotesVisible: false,
    TotalUnits: 15,
    TotalPrice: 78.96,
    TotalCost: 75,
    ConvertedTotalPrice: 78.96,
    ConvertedTotalCost: 75,
    CreateDate: '2022-05-04T15:45:03.18Z',
    CreatedBy: 'Franklin Arsenault',
    UpdateDate: '2022-05-04T15:45:33.757Z',
    UpdatedBy: 'Franklin Arsenault',
    CustomFields: {
      Values: {},
    },
    QuantityOrdered: 0,
  },
  {
    Id: 504065273,
    CorrelationId: '5ad411c3-0bc8-49bd-bbab-35ac0838b432',
    Type: 'product',
    Name: 'Test',
    Description: '',
    Relationships: [],
    TaxRates: [
      {
        Id: 503968251,
        Type: 'Other',
        Rate: 6,
      },
    ],
    Sequence: 0,
    CurrencyCode: 'USD',
    CurrencySymbol: '$',
    ConversionRate: 1,
    Totals: {
      Units: 0,
      Amount: 0,
      Cost: 0,
      Margin: 0,
      TaxableAmount: 0,
      SalesTax: 0,
      TaxRate: 6,
    },
    ConversionTotals: {
      Amount: 0,
      Cost: 0,
      Margin: 0,
      TaxableAmount: 0,
      SalesTax: 0,
      TaxRate: 6,
    },
    ProductId: 0,
    ImageUrl: '',
    Number: '',
    Supplier: {
      Id: 513567335,
      Name: '#1 We Buy Anything 1',
      IsSupplier: true,
      IsDecorator: false,
      IsAsiMember: false,
      PrimaryEmail: {
        Id: 508605044,
        Address: 'ayay-ron@asicentral.com',
        IsPrimary: true,
        Type: 'Work',
      },
      Emails: [
        {
          Id: 508605044,
          Address: 'ayay-ron@asicentral.com',
          IsPrimary: true,
          Type: 'Work',
        },
      ],
      PrimaryPhone: '215-555-5555',
    },
    Categories: [
      {
        Code: 'A01010003   ',
        Name: '3-D PRODUCTS',
      },
    ],
    CPN: '',
    ShippingGroup: 0,
    ChargeTaxesOnShipping: false,
    Status: 'Open',
    VendorNotesVisible: false,
    TotalUnits: 0,
    TotalPrice: 0,
    TotalCost: 0,
    ConvertedTotalPrice: 0,
    ConvertedTotalCost: 0,
    CreateDate: '2022-05-05T12:21:37.997Z',
    CreatedBy: 'Franklin Arsenault',
    CustomFields: {
      Values: {},
    },
    Variants: [],
    ServiceCharges: [],
    Decorations: [],
    QuantityOrdered: 0,
  },
  {
    Id: 504065798,
    CorrelationId: 'a2a560c2-0937-4b65-95d7-62a74c60d113',
    Type: 'product',
    Name: 'xcvxcvxcvxcv',
    Description: '',
    Relationships: [],
    TaxRates: [
      {
        Id: 503968753,
        Type: 'Other',
        Rate: 6,
        Name: '',
      },
    ],
    Sequence: 0,
    CurrencyCode: 'USD',
    CurrencySymbol: '$',
    ConversionRate: 1,
    Totals: {
      Units: 0,
      Amount: 0,
      Cost: 0,
      Margin: 0,
      TaxableAmount: 0,
      SalesTax: 0,
      TaxRate: 6,
    },
    ConversionTotals: {
      Amount: 0,
      Cost: 0,
      Margin: 0,
      TaxableAmount: 0,
      SalesTax: 0,
      TaxRate: 6,
    },
    ProductId: 0,
    ImageUrl:
      'https://commonmedia.uat-asicentral.com/orders/Artwork/81e5403c66f748ebb01b41303a5d6588.png',
    Number: '',
    Supplier: {
      Id: 513550046,
      Name: '000000000123',
      IsSupplier: true,
      IsDecorator: false,
      IsAsiMember: false,
      PrimaryEmail: {
        Id: 508599300,
        Address: 'asdsad@asdsad.ds',
        IsPrimary: true,
        Type: 'Work',
      },
      Emails: [
        {
          Id: 508599300,
          Address: 'asdsad@asdsad.ds',
          IsPrimary: true,
          Type: 'Work',
        },
        {
          Id: 508599636,
          Address: 'x@x.com',
          IsPrimary: false,
          Type: 'Work',
        },
      ],
      PrimaryPhone: '444333444',
    },
    Decorations: [
      {
        Id: 503079897,
        LogoColors: [],
        RepeatLogo: false,
        ProofType: 'Blank',
        CommentsVisible: false,
        InstructionsVisible: false,
        Instructions: '',
        Status: 'Open',
        Details: [
          {
            Id: 505310734,
            VariantLinkType: 'All',
            InstructionsVisible: false,
          },
        ],
        ServiceCharges: [],
        Totals: {
          Amount: 0,
          Cost: 0,
          Margin: 0,
        },
      },
    ],
    Categories: [],
    CPN: '',
    ShippingGroup: 0,
    ChargeTaxesOnShipping: false,
    Status: 'Open',
    VendorNotesVisible: false,
    TotalUnits: 0,
    TotalPrice: 0,
    TotalCost: 0,
    ConvertedTotalPrice: 0,
    ConvertedTotalCost: 0,
    CreateDate: '2022-05-17T11:16:39.153Z',
    CreatedBy: 'Franklin Arsenault',
    UpdateDate: '2022-05-17T11:17:29.36Z',
    UpdatedBy: 'Franklin Arsenault',
    CustomFields: {
      Values: {},
    },
    Variants: [],
    ServiceCharges: [],
    QuantityOrdered: 0,
  },
];
